### ISSUE TITLE
Can't discover BG5 and BP7S devices

### ISSUE THREAD

**Issue by ivl** [iHealthDeviceLabs/iHealthDeviceLabs-Android#10]
I am trying to discover BG5 AND BP7S devices without any luck
No problem in discovering PO3M. Can you help please?

**Comment by Frasprite** [comment]
@ivl dude, you need to add more info and clue about your problem.
**I'm not from iHealth staff or whatever**, but at least give more info, like:
- Android version on device
- Android device used for test / prod (not relevant, but can help a little)
- iHealth SDK used
- iHealth device firmware
- code used in your example
- log (if any and / or even if there is no error stack trace)

Those info will help a lot iHealth dev! I hope you will understand my point of view ;-) .

**Comment by jzhw0130** [comment]
@Frasprite   Thanks for your help.

@ivl 
Did you pair BG5 and BP7S with your phone on bluetooth page?

PO3M support bluetooth low energy, no need to pair.
But BG5 and BP7S support bluetooth 3.0,  you have to do the pair on bluetooth page , then launch your app to discover.
