### ISSUE TITLE
How to gather HS3 / HS4S devices battery status?

### ISSUE THREAD

**Issue by Frasprite** [iHealthDeviceLabs/iHealthDeviceLabs-Android#11]
Hi,

BePATIENT DEV team here.
We are current testing your v2.3.0 of your Android SDK.
We would like to gather  **HS3 / HS4S** devices battery status and we are using following code:

```
mHs3control = iHealthDevicesManager.getInstance().getHs3Control(deviceMac);
mHs4sControl = iHealthDevicesManager.getInstance().getHs4sControl(deviceMac);
```

But we don't see any method from the list showed with the auto-completion or in the API doc.
Can you please help us?

Thank you in advance,
BePATIENT DEV Team

**Comment by jzhw0130** [comment]
@Frasprite 
Sorry
There is no api to gather the battery of HS3/HS4S.
But, if the battery is low energy, you will get a callback.
The action is :  HsProfile.ACTION_ERROR_HS
The key is: HsProfile.ERROR_NUM_HS
The value as follows:
/**
     * Flag Error number of Hs device. **160 low power;** 224： Er0；225 Er1；226： Er2；231：
     * Er7；232：Er8；233：Er9；600：communication error；700：communication timeout
     */

**Comment by jzhw0130** [comment]
@Frasprite 
Moreover,  why did you choose HS3?  HS4S is our latest version of scale.

**Comment by Frasprite** [comment]
@jzhw0130 
Thank you, I will give it a try.
So **160 low power** is the message and if I'm correct _160_ is the level of battery?

At the moment one of our client is using HS3 devices.
That contract was signed long time ago, by my colleagues and HS4S was not released yet.
The client can't change all of his devices, ATM, but I hope that he will do it in the future.

**Comment by jzhw0130** [comment]
@Frasprite 

OK
 Any problem. Feel free to contact me.
