### ISSUE TITLE
Can't connect to PO3?

### ISSUE THREAD

**Issue by 4ctarus** [iHealthDeviceLabs/iHealthDeviceLabs-Android#12]
Hello,

I'm trying to connect on PO3 device to retrieve data, but i get a DEVICE_STATE_CONNECTIONFAIL.
Here is the step i do:
- first i init sdk

`iHealthDevicesManager.getInstance().init(this.context);`
- then i register a callback, set a user and start to discover device(s)

` callbackId = iHealthDevicesManager.getInstance().registerClientCallback(iHealthDevicesCallback);
  iHealthDevicesManager.getInstance().sdkUserInAuthor(context, userName, clientId, clientSecret, callbackId);
iHealthDevicesManager.getInstance().startDiscovery(device);
 `
- and, when i found a device i try to connect to him

`iHealthDevicesManager.getInstance().connectDevice(userName, mac)`
`po3Control = iHealthDevicesManager.getInstance().getPo3Control(mac);`

( this steps work for HS4S, and BP7)

Thank you in advance,

**Comment by jzhw0130** [comment]
@4ctarus 

Hi

What's your phone brand and phone os version?
Because PO3 use bluetooth low energy, os version should be 4.4+.
Moreover, cloud you give me the log on  the logcat?

Jing

**Comment by 4ctarus** [comment]
Hi @jzhw0130,

i'm running my app with a Xiaomi Mi4c on android 5.1.1
here is my log : 

> 07-22 14:14:40.263 20424-20424/com.example.gaben.appbariatric I/Runtime_ble: scan:true
07-22 14:14:40.263 20424-20424/com.example.gaben.appbariatric D/BluetoothAdapter: startLeScan(): null
07-22 14:14:40.273 20424-20443/com.example.gaben.appbariatric D/BluetoothLeScanner: onClientRegistered() - status=0 clientIf=5
07-22 14:14:40.773 20424-20424/com.example.gaben.appbariatric D/IHealthDevice: 34B1F7CD4CEB PO3
07-22 14:14:40.773 20424-20424/com.example.gaben.appbariatric D/IotFragment: datacallback : {"scanned":[{"mac":"34B1F7CD4CEB","type":"PO3"}],"connected":[],"msg":[]}
07-22 14:14:40.783 20424-20424/com.example.gaben.appbariatric I/Runtime_ble: scan:false
07-22 14:14:40.783 20424-20424/com.example.gaben.appbariatric D/BluetoothAdapter: stopLeScan()
07-22 14:14:40.793 20424-20424/com.example.gaben.appbariatric D/BluetoothGatt: connect() - device: 34:B1:F7:CD:4C:EB, auto: false
07-22 14:14:40.793 20424-20424/com.example.gaben.appbariatric D/BluetoothGatt: registerApp()
07-22 14:14:40.793 20424-20424/com.example.gaben.appbariatric D/BluetoothGatt: registerApp() - UUID=bf63f84a-06f3-490d-8886-74036d5c500a
07-22 14:14:40.803 20424-20424/com.example.gaben.appbariatric D/Runtime_ble: Trying to create a new connection.
07-22 14:14:40.803 20424-20424/com.example.gaben.appbariatric D/IHealthDevice: type : PO3 34B1F7CD4CEB
07-22 14:14:40.803 20424-20442/com.example.gaben.appbariatric D/BluetoothGatt: onClientRegistered() - status=0 clientIf=5
07-22 14:14:40.803 20424-20424/com.example.gaben.appbariatric D/IHealthDevice: 34B1F7CD4CEB PO3
07-22 14:14:40.803 20424-20424/com.example.gaben.appbariatric D/IotFragment: datacallback : {"scanned":[{"mac":"34B1F7CD4CEB","type":"PO3"}],"connected":[],"msg":[]}
07-22 14:14:40.803 20424-20424/com.example.gaben.appbariatric I/Runtime_ble: scan:false
07-22 14:14:40.803 20424-20424/com.example.gaben.appbariatric D/BluetoothAdapter: stopLeScan()
07-22 14:14:40.813 20424-20424/com.example.gaben.appbariatric D/BluetoothAdapter: scan not started yet
07-22 14:14:40.883 20424-20424/com.example.gaben.appbariatric I/art: Explicit concurrent mark sweep GC freed 6742(349KB) AllocSpace objects, 0(0B) LOS objects, 17% free, 75MB/91MB, paused 771us total 74.768ms
07-22 14:14:40.893 20424-20424/com.example.gaben.appbariatric D/IHealthDevice: type : PO3 34B1F7CD4CEB

**Comment by 4ctarus** [comment]
the same on a Samung galaxy note 3 on 4.4.2

**Comment by jzhw0130** [comment]
@4ctarus 
Hi, could you give more log? Because the log is less one second, connect success will cost 3-4 seconds.

Moreover, could you give the code you call the Api?
Maybe it will be help for us to solve the problem.


Jing

**Comment by 4ctarus** [comment]
@jzhw0130 

Hi, i can connect now but i got a new error no 'controll found'
there's the log : 
- [Log](http://pastebin.com/BEcvpbgD)

and there's the code : 
- [my activity](http://pastebin.com/2evhWm5N)
- [class who make the ling between ihealth class and other activity](http://pastebin.com/nD7bSSGu)
- [ihealth device gestion](http://pastebin.com/ymkUR0rn)

**Comment by jzhw0130** [comment]
@4ctarus 

Hi

After call connectDevice(), callback   as follows 
@Override
        public void onDeviceConnectionStateChange(String mac, String deviceType, int status, int errorID) {}
will be invoked.

You can get PO3 control in the callback.
Such as:
public void onDeviceConnectionStateChange(String mac, String deviceType, int status, int errorID) {
   if (status == iHealthDevicesManager.DEVICE_STATE_CONNECTED) {
           if ("BP7".equals(type)) {
                bp7Control = iHealthDevicesManager.getInstance().getBp7Control(mac);
            } else if ("HS4S".equals(type)) {
                hs4sControl = iHealthDevicesManager.getInstance().getHs4sControl(mac);
            } else if ("PO3".equals(type)) {
                po3Control = iHealthDevicesManager.getInstance().getPo3Control(mac);
            }
   }
      
}

**Comment by 4ctarus** [comment]
@jzhw0130 
Thank you so much, it works great. Now i can get the battery status but the gethistorydata() and startmeasuredata() functions, seem to return nothing.

**Comment by jzhw0130** [comment]
Hi

Did you put your finger into PO3?
And did PO3 display result on screen?

If you call startmeasuredata(), callback should be triggered.

public void onDeviceNotify(String mac, String deviceType, String action, String message) {
        case PoProfile.ACTION_LIVEDA_PO:
        case PoProfile.ACTION_RESULTDATA_PO:
}
Maybe you can send me more logs, after you call startmeasuredata() and gethistorydata().


jing

**Comment by jzhw0130** [comment]
@4ctarus 

Moreover, maybe you can try our demo for sdk.   It works well.

**Comment by Denten7** [comment]
Hi,

I'm trying to get data from PO3 device with your android sdk demo. While scanning for devices, my LG phone finds the device, but when I want to connect with the device I always get "Haven't permission to connect this device or the mac is invalid" message. For skd identification I'm using your userName so the identification should work. I don't know where is the problem?

**Comment by 4ctarus** [comment]
@jzhw0130 

Hi,
I come to you again because it finaly work, just a dumb error from me, didn't think i have to press the button to start the device.

Big thanks to you.

**Comment by 4ctarus** [comment]
@Denten7 

hello, 
What did you mean by "your username" ?

**Comment by Denten7** [comment]
Hi,

Sorry I should be more clearer. I meant that I did not change userName, client ID and client secret variables, because they were already in the code so I thought this should work for demo purposes. Is this a problem? Should I use my userName, client ID and client secret?

**Comment by 4ctarus** [comment]
@Denten7 

try with your id, i reminded i've try with the sdk id, without success.
