### ISSUE TITLE
Problem connecting PO3

### ISSUE THREAD

**Issue by Denten7** [iHealthDeviceLabs/iHealthDeviceLabs-Android#14]
Hi,

I have a problem with connecting to PO3 device. I'm using your demo and everytime I want to connect to the device, I get a message "Haven’t permission to connect this device or the mac is not valid". How can I solve this problem? 

Thank you

**Comment by jzhw0130** [comment]
@Denten7 

Hi,
You have to get the permission by calling the api as follows:
iHealthDevicesManager.getInstance().sdkUserInAuthor(MainActivity.this, userName, clientId,
                        clientSecret, callbackId);

**Comment by Denten7** [comment]
I've done that. This api call happens when I press button Certification but the result is the same. Is it possible that the problem is in my clientID and client secret? Because when I registered my application there were only push and pull model options in Integration Method section. There was no Android SDK model or IOS SDK model option available.

**Comment by jzhw0130** [comment]
@Denten7 

Sure

Your clientID is invalidate now. When register the application, you have to select 'Android' mode.
If you are a developer in Europe, please send a email to louie@ihealthlabs.com.
Else send a email to yifan.liu@ihealthlabs.com.
He will send a invitation to you.

Jing

**Comment by Denten7** [comment]
@jzhw0130 

This is it. Thank you for your informations and support.

Denis

**Comment by jzhw0130** [comment]
@Denten7 
ok      
Any problem, feel free to contact us.

Thanks
