### ISSUE TITLE
Android permission explaination

### ISSUE THREAD

**Issue by Frasprite** [iHealthDeviceLabs/iHealthDeviceLabs-Android#15]
Hi

Francesco, from BePATIENT DEV team here.
One of our client asked us to describe why we need some permission on our Android application.
I was able to explain the purpose of each permission, see snippet below:
```
    <!-- Internet communication and detect / manage Wi-Fi state -->
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.CHANGE_WIFI_STATE" />

    <!-- Bluetooth permission for communicating with health devices -->
    <uses-permission android:name="android.permission.BLUETOOTH" />
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />

    <!-- Permission for writing on device memory -->
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

    <!-- Permission for locating user device in order to search beacons -->
    <!-- https://developer.android.com/reference/android/bluetooth/le/BluetoothLeScanner.html#startScan(android.bluetooth.le.ScanCallback) -->
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />

    <!-- Other permission -->
    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" /> 
```
[READ_PHONE_STATE](https://developer.android.com/reference/android/Manifest.permission.html#READ_PHONE_STATE) and [RECORD_AUDIO](https://developer.android.com/reference/android/Manifest.permission.html#RECORD_AUDIO) are well explained in official documentation, but I don't understand how can I describe to the client why we need them.

This is not an issue, of course, but can you please give us more info about their required presence? Is it possible to delete them from our application?

Thank you in advance,
Francesco

**Comment by jzhw0130** [comment]
@Frasprite 

RECORD_AUDIO  used for iHealth BG1 device (which connect with phone by headphone jack).
Without BG1 device, you can delete the permission.

READ_PHONE_STATE used to read the region and language from the phone's settings. With the region and language, we choose the best iHealth server to verify  the clientID clientSecret username.


Jing

**Comment by Frasprite** [comment]
@jzhw0130 

Perfect, thank you.

Francesco
