### ISSUE TITLE
iHealthDevicesManager.getInstance().destroy(); explaination

### ISSUE THREAD

**Issue by Frasprite** [iHealthDeviceLabs/iHealthDeviceLabs-Android#18]
Hello,

Francesco from BePATIENT DEV team.
I need some info about this method:
```
iHealthDevicesManager.getInstance().destroy();
```

This was always available on previous iHealth SDK and also on latest one (2.3), but not used on example code.

What's the purpose of this method?
Is this useful in order to close correctly Bluetooth connection or DeviceManager instance?

Thank you in advance for your help.
Francesco

**Comment by jzhw0130** [comment]
@Frasprite 

Yes, It is used to close the connection \ clear the callback\ clear some cache
After call destroy(), you have to call init() \register callback again when you want to connect device again.

Jing

**Comment by Frasprite** [comment]
Thank you Jing.
