### ISSUE TITLE
Can't connect to HS4 scale

### ISSUE THREAD

**Issue by ivl** [iHealthDeviceLabs/iHealthDeviceLabs-Android#2]
Using demo application i was able to connect to tacker AM3S. But can't discover HS4.

From logs I can see that Android can find scale but can’t determine that its HS4
I/ihealthDeviceManager: name:Body Scale - address:90:59:AF:23:FB:49 - serviceUuid: 636f6d2e-6a69-7561-6e2e-425753563031

I was able to discover HS4 only in one case - when turn on/of Bluetooth on phone. But in this case - its not possible to connect to device.
Can you help please?
Thanks

**Comment by jzhw0130** [comment]
Fix now, please update 
@ivl
