### ISSUE TITLE
onScanDevice() is not getting called sometimes

### ISSUE THREAD

**Issue by manikavi** [iHealthDeviceLabs/iHealthDeviceLabs-Android#23]
Hi,
     **onScanDevice**() is not getting called sometimes.Can anyone help me to find reason for this?,mac and deviceType is correct

```
 public com.ihealth.communication.manager.iHealthDevicesCallback iHealthDevicesCallback = new iHealthDevicesCallback() {

        @Override
        public void onScanDevice(String mac, String deviceType, int rssi) {
}
}
```

**Comment by qqskim** [comment]
Hi

Could you supply more details about your question?

eg.

Copy your code which call the Api of SDK..

**Comment by manikavi** [comment]
@qqskim , not getting log for this now,If i get in future i will replicate
