### ISSUE TITLE
Push OffLine values before doing online measurement in Hs4s 

### ISSUE THREAD

**Issue by manikavi** [iHealthDeviceLabs/iHealthDeviceLabs-Android#26]
Hi ,
  I want to push all offline reading from **HS4S** device before taking online measurement,Here is my code [HS4S.txt](https://github.com/iHealthDeviceLabs/iHealthDeviceLabs-Android/files/504094/HS4S.txt),

**Issue which i'm getting from this code:**

    1. not getting online measurement values after pushing all offline measurements

Can i get help to resolve this ?

**Comment by jzhw0130** [comment]
case HANDLER_OFFLINE_RESULT:
if (mHs4sControl == null) {
         Log.i("mHs4Control == null","mHs4Control == null" );

     } else {
         mHs4sControl.measureOnline(1, usrId);
     }
break;

**Comment by manikavi** [comment]
This is working,I want to make sure  this doubt,I taken two offline and one online reading,"historicaldata_hs" is having both online and offline reading?,I am posting all entries to DB,In this case I'm posting 4 entries(1 will be duplicate entry).Please correct me if i'm wrong



This json is from **historicaldata_hs** action :

```
{
"historyData":[
{
"dataID":"7BF43DC958FF3CEAC59A889AB5C07F2A",
"date":"2016-10-01 13:50:24",
"value":**12.300000190734863  - OFFLINE**
},
{
"dataID":"E0EFDCC32B3728BAB2263FD2F9283194",
"date":"2016-10-01 13:50:39",
"value":**10.600000381469727 - OFFLINE**
},
{
"dataID":"45CB67F45C6AAF5B149FC308A446FCCA",
"date":"2016-10-01 13:53:38",
"value":**8.899999618530273 - ONLINE**
}
]
}
```
This  is from **online_result_hs** action :
```

{
"value":**8.899999618530273 - ONLINE**,
"dataID":"74376CC501971E9CD7D066037D90F1C7"
}
```

**Comment by jzhw0130** [comment]
Sure

It is a bug, we have fixed it , but have not update the version on Github.
For the next version, we will update .

You can use the beta version as follows

[Uploading iHealthLibrary_2.3.0.26.jar.zip…]()

**Comment by jzhw0130** [comment]
[iHealthLibrary_2.3.0.26.jar.zip](https://github.com/iHealthDeviceLabs/iHealthDeviceLabs-Android/files/504257/iHealthLibrary_2.3.0.26.jar.zip)

**Comment by jzhw0130** [comment]
@manikavi 

What about the beta version ?

**Comment by manikavi** [comment]
@jzhw0130 ,Still i didn't use that ,will check and let you know

**Comment by manikavi** [comment]
@jzhw0130 ,Same from new version also,here "**9.300000190734863**" is online reading

```
{
"historyData":[
{
"dataID":"90838CBD5C8903F21369EBA7A997EE56",
"date":"2016-10-03 12:12:00",
"value":7.900000095367432
},
{
"dataID":"3886A8D90D4856A040DF6DC98BCE3F30",
"date":"2016-10-03 12:12:11",
"value":6
},
{
"dataID":"01216C8437CDE222186C70E1AC41D51D",
"date":"2016-10-03 12:13:13",
"value":9.300000190734863
}
]
}
```

**Comment by jzhw0130** [comment]
@manikavi 

Sorry  I forget to update the code from SVN.
Try the new version as follows:
[iHealthLibrary_2.3.0.26.jar.zip](https://github.com/iHealthDeviceLabs/iHealthDeviceLabs-Android/files/505665/iHealthLibrary_2.3.0.26.jar.zip)

**Comment by manikavi** [comment]
@jzhw0130 , Same Logs


`D/HS4S: mac:8CDE529FB54E--type:HS4S--action:historicaldata_hs--message:{"historyData":[{"dataID":"B7612100133CEC03BA11D67BCF4E8C36","date":"2016-10-03 12:48:56","value":7.5},{"dataID":"F1C4C066C8AB9735BE913A5E6E76789D","date":"2016-10-03 12:49:08","value":9},{"dataID":"89354DE6887569A6CFF2236D56E01B4F","date":"2016-10-03 12:49:42","value":5.800000190734863}]}`

`D/HS4S: mac:8CDE529FB54E--type:HS4S--action:online_result_hs--message:{"value":5.800000190734863,"dataID":"EA28B31AE63C89449B229AADC329718A"}`

**Comment by jzhw0130** [comment]
@manikavi 

Sorry, I have no HS4S at home, I  will try the problem on work day .
Late to reply.

**Comment by manikavi** [comment]
Issue is fixed ,Check this link for more info,

[https://github.com/iHealthDeviceLabs/iHealthDeviceLabs-Android/issues/29](url)
