### ISSUE TITLE
calling getHistoryData() is getting history entries from PO3

### ISSUE THREAD

**Issue by manikavi** [iHealthDeviceLabs/iHealthDeviceLabs-Android#27]
Hi,
   getHistoryData() is not calling onDeviceNotify() in PO3.Here is my Code,Can any one help me to resolve this?

[mPO3.txt](https://github.com/iHealthDeviceLabs/iHealthDeviceLabs-Android/files/504104/mPO3.txt)

**Comment by jzhw0130** [comment]
No problem with your code.

**Comment by manikavi** [comment]
How to troubleshoot this issue?

**Comment by jzhw0130** [comment]
As issues 25

https://github.com/iHealthDeviceLabs/iHealthDeviceLabs-Android/issues/25
