### ISSUE TITLE
Taking offline measurement in  BG5

### ISSUE THREAD

**Issue by manikavi** [iHealthDeviceLabs/iHealthDeviceLabs-Android#28]
Hi,

Can  BG5 measurements  be taken without a mobile device?
     Yes. After the meter is synced with your mobile device, you may use the meter when your mobile device is not available. The measurement data will be stored in the meter.              

**For taking offline measurement I've done this** 
            
  How to sync mobile with BG5,I did scan and pair,after pairing i inserted strips to BG  device,But I got ErE, But  strip is not expired,Can i get help from you guys to solve my problem?

**Comment by jzhw0130** [comment]
You should scan the QR on bottle, then send the code to BG5. After done, you can start measure.

[BG5-FlowChart.pdf](https://github.com/iHealthDeviceLabs/iHealthDeviceLabs-Android/files/504262/BG5-FlowChart.pdf)

**Comment by manikavi** [comment]
@jzhw0130 ,I tried this from ihealth Gluco app ,first i taken online measurement,then switched off BT in my mobile,taken offline(*actually didnt get any confirmation message on BG5 device screen display).Please send me the steps for taking offline measurement with out using android phone?

**Comment by jzhw0130** [comment]
@manikavi 
For measure offline, did you insert the strip to BG5?  If you do , take a photo for BG5. thanks

**Comment by manikavi** [comment]
![img_20161005_113915206](https://cloud.githubusercontent.com/assets/6669647/19102784/ddbc99e0-8aa0-11e6-9a72-3372c58ad833.jpg)

**Comment by jzhw0130** [comment]
@manikavi 
Then you can use the test strip to inhalate the control solution.
BG5 will display a blood symbol， then 5-4-3-2-1-result.

**Comment by manikavi** [comment]
@jzhw0130 , I want to take with blood sample,Please help me to do with correct steps

![unnamed](https://cloud.githubusercontent.com/assets/6669647/19103919/cd26a39e-8aa7-11e6-8847-1ca1e7e79dc2.jpg)

**Comment by manikavi** [comment]
@jzhw0130 ,There?

**Comment by qqskim** [comment]
Hi

Did you  do a measure online successfully with iHealth iGluco App?
Did you scan the QR code on  the strip bottle?

**Comment by manikavi** [comment]
Hi,
  yes,done both

**Comment by manikavi** [comment]
@qqskim , Plese check screen shot for online measurements

![connected](https://cloud.githubusercontent.com/assets/6669647/19104813/992914b4-8aac-11e6-9dc7-532c668d5b2a.jpg)


![stripinserted](https://cloud.githubusercontent.com/assets/6669647/19104814/992c94d6-8aac-11e6-9f8d-3bd9a1aa28d8.jpg)


![readingtaken](https://cloud.githubusercontent.com/assets/6669647/19104815/992e94de-8aac-11e6-9394-0f83d619423c.jpg)

**Comment by qqskim** [comment]
ok

Your online measurement is right.
Did you do the offline measurement with the same strip or a new one?  With a used strip, BG5 will display error message.

**Comment by manikavi** [comment]
@qqskim ,
           using new strips,Could you please take offline reading and send screenshot.

**Comment by manikavi** [comment]
@qqskim, 10.8 means?, Please let me know when you will be available?

**Comment by qqskim** [comment]
October 8th

**Comment by jzhw0130** [comment]
China

**Comment by manikavi** [comment]
@jzhw0130 , @qqskim ,

            Is there any way to help me to take offline reading?

**Comment by jzhw0130** [comment]
@manikavi 

Do you have a user manual about BG5, maybe you can get some information. 
There is something wrong with your offline measure process, but I do not known why.

Did BG5 always display like the photo( 3 bars) ? Not display any other photo?

**Comment by manikavi** [comment]
@jzhw0130 , I sent video to your mail id ,Please check

**Comment by jzhw0130** [comment]
@manikavi 

Hi


Maybe I  get the problem.

Make sure BG5 is closed, then do not press the button to open.  Insert the strip to BG5 directly, BG5 will open automatically.

Attentation: Do not press the button to open.

**Comment by manikavi** [comment]
@jzhw0130 , Thanks for your time and help
