### ISSUE TITLE
Getting two different bottle IDs from BG5

### ISSUE THREAD

**Issue by manikavi** [iHealthDeviceLabs/iHealthDeviceLabs-Android#29]
Hi,
  Getting two different bottle IDs from BG5 device alternatively.What could be the reason for this?

**Comment by qqskim** [comment]
Because bottle id is the identify for every bottle strip. You have to send the special QR code to BG5, then the measure result is accurate.

**Comment by manikavi** [comment]
@qqskim ,
I 've added my code,Please let me know whether i'm in correct track

[bg5code.txt](https://github.com/iHealthDeviceLabs/iHealthDeviceLabs-Android/files/505672/bg5code.txt)

**Comment by jzhw0130** [comment]
Same problem with PO3
One by one, not as follows:
`		if(bg5Control != null){
			bg5Control.getBattery();
            bg5Control.setTime();
            bg5Control.setUnit(1);

            bg5Control.getBottleId();

		//	bg5Control.startMeasure(1);

		}
		else{
            Log.d(TAG, "bg5Control == null");

		}`

**Comment by manikavi** [comment]
@jzhw0130 ,
          I modified my po3 code ,but still i cant able to get history,Please check,Checked in Demo also,I have added my Sample code here

[po3Code_after_modifiction.txt](https://github.com/iHealthDeviceLabs/iHealthDeviceLabs-Android/files/505726/po3Code_after_modifiction.txt)

**Comment by qqskim** [comment]
Upload your log

**Comment by manikavi** [comment]
@qqskim , Can't able to send logs,my PO3 device is hanged

![po3](https://cloud.githubusercontent.com/assets/6669647/19034007/44395f8c-892f-11e6-9793-e415aef9ead2.png)

**Comment by qqskim** [comment]
Press the button on PO3 for 5 seconds, PO3 will reset.

**Comment by manikavi** [comment]
@qqskim ,
   I 've added log from Sample ihealth code ,Please check

[ihealth_po3_code.txt](https://github.com/iHealthDeviceLabs/iHealthDeviceLabs-Android/files/506316/ihealth_po3_code.txt)

[ihealth_po3_log.txt](https://github.com/iHealthDeviceLabs/iHealthDeviceLabs-Android/files/506314/ihealth_po3_log.txt)

**Comment by jzhw0130** [comment]
@manikavi 

I need more help from you.  I make a beta version with more logs, you can try with the version, then upload the logs. It will be help for me to get your problem.

Repeat your problem with PO3 and HS4S with the log version of SDK.

Thanks.

[iHealthLibrary_2.3.0.26_log.jar.zip](https://github.com/iHealthDeviceLabs/iHealthDeviceLabs-Android/files/507847/iHealthLibrary_2.3.0.26_log.jar.zip)

**Comment by manikavi** [comment]
@jzhw0130 ,Please Check ,Sorry for delay

[new_hs4s_log.txt](https://github.com/iHealthDeviceLabs/iHealthDeviceLabs-Android/files/507997/new_hs4s_log.txt)
[new_po3_log.txt](https://github.com/iHealthDeviceLabs/iHealthDeviceLabs-Android/files/507998/new_po3_log.txt)

**Comment by jzhw0130** [comment]
@manikavi 
Thanks for your help.

From the log,  I get the problem of HS4S, make a new beta version for you to try again.

For the problem of PO3, you need to wait more time to get the history, because there is so many offline measure results stored in PO3(99 records). For the log, SDK only get 54 records when you close the app. 

It costs 42 seconds to upload 54 records, so maybe you have to wait at least 80 seconds to upload all 99 records.
[iHealthLibrary_2.3.0.26_log.jar.zip](https://github.com/iHealthDeviceLabs/iHealthDeviceLabs-Android/files/508506/iHealthLibrary_2.3.0.26_log.jar.zip)

**Comment by manikavi** [comment]
@jzhw0130 ,Please Check this Log,I taken online measurement first,then switched off blue tooth in my mobile,taken offline measurement,then connected PO3 and mobile for pushing all off line reading but app terminated.


[po3_start_measure_log.txt](https://github.com/iHealthDeviceLabs/iHealthDeviceLabs-Android/files/510052/po3_start_measure_log.txt)

**Comment by manikavi** [comment]
@jzhw0130 ,check this Log,now i can able to get value ,both offline and online reading is coming from **historicaldata_hs** action,there is no use of keeping **online_result_hs** action .Please Let me know if i'm wrong?

[700_error_hs4s_log.txt](https://github.com/iHealthDeviceLabs/iHealthDeviceLabs-Android/files/510068/700_error_hs4s_log.txt)

**Comment by jzhw0130** [comment]
@manikavi 
For HS4S problem， have you been standing on HS4S when you call measureOnline()?  The result displayed on HS4S is changing or stabled?

Do as follows:
Connect HS4S with your app, call getOfflineData() to upload offline data.
Call measureOnline() to start a measure online, then stand on HS4S now.

**Comment by manikavi** [comment]
@jzhw0130 ,

For HS4S problem， 
have you been standing on HS4S when you call measureOnline()?  - Sitting in chair,
The result displayed on HS4S is changing or stabled? - stable

**Comment by manikavi** [comment]
@jzhw0130 ,Thanks a lot ,Please help me for Po3 and BG5 offline measurement

**Comment by jzhw0130** [comment]
@manikavi 

Try the new version  for PO3, thanks 

[iHealthLibrary_2.3.0.26_log.jar.zip](https://github.com/iHealthDeviceLabs/iHealthDeviceLabs-Android/files/510176/iHealthLibrary_2.3.0.26_log.jar.zip)

**Comment by manikavi** [comment]
@jzhw0130 , 404 error,But im already using this jar

**Comment by jzhw0130** [comment]
@manikavi  I cannot follow you.
PO3 ?  BG5?  Where did you get 404?
The latest beta version?

**Comment by manikavi** [comment]
@jzhw0130 

[https://github.com/iHealthDeviceLabs/iHealthDeviceLabs-Android/files/510176/iHealthLibrary_2.3.0.26_log.jar.zip](url)

**Comment by jzhw0130** [comment]
[iHealthLibrary_2.3.0.26_log.jar.zip](https://github.com/iHealthDeviceLabs/iHealthDeviceLabs-Android/files/510405/iHealthLibrary_2.3.0.26_log.jar.zip)

**Comment by manikavi** [comment]
Thanks a lot for your help @jzhw0130
