### ISSUE TITLE
Cant connect to "BP5 08B6E5" device.

### ISSUE THREAD

**Issue by manikavi** [iHealthDeviceLabs/iHealthDeviceLabs-Android#3]
Using  SDK 2.0 demo application i was unable to connect BP5 device .getting "null" from 

**bp5Control = iHealthDevicesManager.getInstance().getBp5Control(deviceMac);** 
*deviceMac - I'm sending proper MAC address

----
If I Use SDK 1.0 ,I am getting mismatch error in **ClientId,ClientSecret,UserId**(Status is 5)

can i get help to resolve this issue?

Thanks,

**Comment by jzhw0130** [comment]
@manikavi 
Hi，did you try our demo with BP5?

It is different between SDK 1.0 and SDK 2.0.
For SDK 2.0, you have to connect step by step:
1. Valid your clientID clientSecret UserName
2. discovery BP5
3. connect BP5
4. get BP5 control
5. call Api from BP5 control


Moreover, what's your clientID and clientSecret? 
Email: jingzhiwei@ihealthlabs.com.cn

**Comment by manikavi** [comment]
Hi,
   I have sent my credentials to your mailId,Yes I tried SDK2.0,In code you are showing all  devices in ListView,But If i run demo app,i cant able to see BP5 device in that listview,so i created new button view for connecting to BP5 device,then Inside onclicklisterner i added this code

               **Intent intent = new Intent();
                intent.setClass(MainActivity.this, BP5.class);
                intent.putExtra("mac", "XXXXXXXXXXX");
                startActivity(intent);

as i sent before,inside **BP5.class,**I'm getting **null** after executing below line of code
```

/* Get bp5 controller */
		bp5Control = iHealthDevicesManager.getInstance().getBp5Control(deviceMac);
```

**Comment by jzhw0130** [comment]
@manikavi 

Hi,
1. Valid your clientID clientSecret UserName

callbackId = iHealthDevicesManager.getInstance().registerClientCallback(miHealthDevicesCallback);
iHealthDevicesManager.getInstance().sdkUserInAuthor(MainActivity.this, userName, clientId,
                        clientSecret, callbackId);
2. discovery BP5
    Call:
     int type = iHealthDevicesManager.DISCOVERY_BP5;
     iHealthDevicesManager.getInstance().startDiscovery(type);

    Callback:
    Override
        public void onScanDevice(String mac, String deviceType, int rssi) {
            Log.i(TAG, "onScanDevice - mac:" + mac + " - deviceType:" + deviceType + " - rssi:" + rssi);
        }
3. connect BP5
    Call:
     boolean req = iHealthDevicesManager.getInstance().connectDevice(userName, mac);
                if (!req) {
                    Toast.makeText(MainActivity.this, "Haven’t permission to connect this device or the mac is  not valid", Toast.LENGTH_LONG).show();
                }

      Callback:
      @Override
        public void onDeviceConnectionStateChange(String mac, String deviceType, int status, int errorID) {
        }
4. get BP5 control
     Call:
     /* Get bp5 controller */
        bp5Control = iHealthDevicesManager.getInstance().getBp5Control(deviceMac);
5. call Api from BP5 control


Maybe you can send your demo code, we will check to get the problem.

**Comment by manikavi** [comment]
**@jzhw0130**

**1. Valid your clientID clientSecret UserName : ** I am getting status as 2 ,means "USER LOGGED SUCCESSFULLY",so there is no problem with credentials

**2. discovery BP5 : **
onScanDevice()  is not calling.Please find  Log here,

I'm using
 Android **Moto G**,Version is **5.1**
 ihealth BP device model is : **BP5 08B6E5**

06-16 12:09:41.205: I/Runtime_ble(1750): scan:true
06-16 12:09:41.205: D/BluetoothAdapter(1750): startLeScan(): null
06-16 12:09:41.209: D/BluetoothLeScanner(1750): onClientRegistered() - status=0 clientIf=5
06-16 12:09:53.231: I/Runtime_ble(1750): scan:false
06-16 12:09:53.231: D/BluetoothAdapter(1750): stopLeScan()

----------------------------
I just made changes in mainactivity file.So I added only this file

[mainactivitybp5samplecode.pdf](https://github.com/iHealthDeviceLabs/iHealthDeviceLabs-Android/files/317801/mainactivitybp5samplecode.pdf)

**Comment by jzhw0130** [comment]
@manikavi 
Hi

Do you register the callback:
callbackId = iHealthDevicesManager.getInstance().registerClientCallback(miHealthDevicesCallback);

Pair BP5 with your Phone on bluetooth list?

**Comment by manikavi** [comment]
**@jzhw0130**

By default,**callbackId**  is assigning right?

**Comment by jzhw0130** [comment]
Sure.
You can read the demo code, we have test the demo, it works well now.

**Comment by manikavi** [comment]
**@jzhw0130**

Thanks I'm getting reading 

Please clarify the Steps,

Step 1: Switch On Bluetooth
Step 2.Authenticate Client-id,Client-secret,mail-id,
Step 3.Manually Scan and Pair ihealth Device 
Step 4.then we have to Click on DEVICE DISCOVERY button in demo app,It means we are discovering already paired ihealth devices,showing that  in ListView


facing one more issue,first time i clicked on listview,it is connecting to ihealth device automatically and taking reading..I try to click on second time Iam getting below logs,can you please check once

```
06-16 12:58:20.945: I/MainActivity(15941): mac = 8CDE5208B6E5
06-16 12:58:20.947: I/Runtime_ble(15941): scan:false
06-16 12:58:20.948: D/BluetoothAdapter(15941): stopLeScan()
06-16 12:58:20.949: D/BluetoothAdapter(15941): scan not started yet
```

**Comment by manikavi** [comment]
**@jzhw0130**

  how much time difference should be there for taking readings?

**Comment by manikavi** [comment]
**@jzhw0130**
   Thanks,Im getting reading

**Comment by jzhw0130** [comment]
@manikavi 
SDK 1.0  discovery and connect automatically. (SDK1.0  is out  of date , please use SDK 2.0)
SDK 2.0 you have to discovery and connect by yourself.

**Comment by manikavi** [comment]
**@jzhw0130**
    yeah I tested both,thanks for your help.

**Comment by jzhw0130** [comment]
OK
Any problem, feel free to contact me. Thanks

**Comment by manikavi** [comment]
**@jzhw0130**
                     Sure
