### ISSUE TITLE
Getting error_num 15 From BG5 

### ISSUE THREAD

**Issue by manikavi** [iHealthDeviceLabs/iHealthDeviceLabs-Android#30]
Hi,
     I'm Getting  **{"error_num":15}** From BG5 ,I searched in docs ,But I didnt get the reason for this error number,Could you please help me to fine Solution?,I need to know the status of  **{"start_mode":2}** also..
```
I/Bg5Demo: deviceType: BG5
I/Bg5Demo: action: action_start_mode
I/Bg5Demo: message: {"start_mode":2}
I/Bg5Demo: mac: 8CDE5211E688
I/Bg5Demo: deviceType: BG5
I/Bg5Demo: action: action_start_measure
I/Bg5Demo: message: {}
D/Bg5Demo:  status start measure
I/Bg5Demo: mac: 8CDE5211E688
I/Bg5Demo: deviceType: BG5
I/Bg5Demo: action: action_measure_error
I/Bg5Demo: message: {"error_num":15}
D/Bg5Demo:  status error num: 15
```

**Comment by qqskim** [comment]
Error code as follows:

/**
 * Flag Error number of Bg5 device.
 * <p>Error code and Description</p>
 * <p>0:Battery is low.</p>
 * <p>1:Glucose test result is out of the measurement range.</p>
 * <p>2:Unknown interference detected, please repeat the test.</p>
 * <p>3:Strip is used or unknown moisture detected, discard the test strip and repeat the test with a new strip..</p>
 * <p>4:Reading transmission error. Repeat the test with a new test strip. If the problem persists, contact iHealth customer service for assistance.</p>
 * <p>5:The environmental temperature is beyond normal range, place the meter at room temperature for at least 30 minutes, then repeat the test.</p>
 * <p>6:The environmental temperature is beyond normal range, place the meter at room temperature for at least 30 minutes, then repeat the test.</p>
 * <p>7:Test strip coding error.</p>
 * <p>8:Communication error, press"START" or rescan the code to repeat the test.</p>
 * <p>9:Strip removed in the middle of reading, repeat the test with a new strip.</p>
 * <p>10:Insert a new test strip and repeat the test.</p>
 * <p>11:Cannot write to SN or KEY.</p>
 * <p>12:Please set time.</p>
 * <p>13:0 test strips remaining.</p>
 * <p>14:Test strip expired.</p>
 * <p>15:Unplug the charging cable before testing.</p>
 * <p>112:Device don't support to query energy.</p>
 * <p>400:Parameters out of range.</p>
 */

**Comment by manikavi** [comment]
@qqskim ,Thanks
