### ISSUE TITLE
startMeasure() is not called in BG5 onlinemesurement

### ISSUE THREAD

**Issue by manikavi** [iHealthDeviceLabs/iHealthDeviceLabs-Android#32]
Hi,
   **startMeasure**() not called ,Please check this log

[bg5_startmeasure_not_called.docx](https://github.com/iHealthDeviceLabs/iHealthDeviceLabs-Android/files/510609/bg5_startmeasure_not_called.docx)

**Comment by jzhw0130** [comment]
For the log, startMeasure(int type) is not called after setBottleMessage() is called.
After call startMeasure(int type) , you can insert the strip into BG5 , take the blood , then get the measure result.

**Comment by manikavi** [comment]
@jzhw0130 , Please check my code,I am calling .more info in attached file


```
else  if (Bg5Profile.ACTION_SET_BOTTLE_MESSAGE_SUCCESS.equals(action)){
                Log.e(TAG, "action_setbottlemessage_success");
                if (bg5Control != null) {
                    Log.d(TAG, "bg5Control != null");
                    bg5Control.startMeasure(1); //Test with Blood
                }else {
                    Log.d(TAG, "bg5Control == null");
                }
            }
```

[bg5_startmeasure_not_called_code.docx](https://github.com/iHealthDeviceLabs/iHealthDeviceLabs-Android/files/510631/bg5_startmeasure_not_called_code.docx)

**Comment by jzhw0130** [comment]
@manikavi 
Did you do the test with 2.3.0 or  2.3.0.26?  If 2.3.0, replace with 2.3.0.26.

For your code, need a little change
1. No need to call setBottleId(),  the function will be implemented in setBottleMessage().
2. Bg5Profile.ACTION_START_MODE is removed
3. You have to call startMeasure( ) on the action: Bg5Profile.ACTION_SET_BOTTLE_MESSAGE_SUCCESS

With the change above, give me new log, thanks

**Comment by manikavi** [comment]
@jzhw0130 ,

FYI - compile files('libs/iHealthLibrary_2.3.0.26_log.jar') - using this jar file


1. No need to call setBottleId(), the function will be implemented in setBottleMessage(). - Done
2. Bg5Profile.ACTION_START_MODE is removed - Done but check  my reply to 
[https://github.com/iHealthDeviceLabs/iHealthDeviceLabs-Android/issues/30](url)
  
3. You have to call startMeasure( ) on the action: Bg5Profile.ACTION_SET_BOTTLE_MESSAGE_SUCCESS - already there

```
else  if (Bg5Profile.ACTION_SET_BOTTLE_MESSAGE_SUCCESS.equals(action)){
                Log.e(TAG, "action_setbottlemessage_success");
                if (bg5Control != null) {
                    Log.d(TAG, "bg5Control != null");
                    bg5Control.startMeasure(1); //Test with Blood
                }else {
                    Log.d(TAG, "bg5Control == null");
                }
            }
```


[bg5_log_as_per_jing_suggestion.docx](https://github.com/iHealthDeviceLabs/iHealthDeviceLabs-Android/files/510940/bg5_log_as_per_jing_suggestion.docx)

**Comment by manikavi** [comment]
@jzhw0130  , you there?

**Comment by manikavi** [comment]
@jzhw0130 ,

I tested with expired strips,Please check attached doc for more logs 

[bg5_online_measurement_with_expired_strip.docx](https://github.com/iHealthDeviceLabs/iHealthDeviceLabs-Android/files/511409/bg5_online_measurement_with_expired_strip.docx)

**Comment by manikavi** [comment]
@jzhw0130 ,check this log ,startmeasure() is calling twice ,Please let me  know whether my app is causing as issue

[bg5_start_measurecalled_two_times.txt](https://github.com/iHealthDeviceLabs/iHealthDeviceLabs-Android/files/511439/bg5_start_measurecalled_two_times.txt)

**Comment by manikavi** [comment]
@jzhw0130 , Please check this Log

[start_measure_not_called_bg5.docx](https://github.com/iHealthDeviceLabs/iHealthDeviceLabs-Android/files/513760/start_measure_not_called_bg5.docx)

**Comment by jzhw0130** [comment]
@manikavi 

Did you try the latest version of SDK above(https://github.com/iHealthDeviceLabs/iHealthDeviceLabs-Android/files/512957/iHealthLibrary_2.3.0.26_log.jar.zip)?
From your log,  the SDK is not the latest.

Please try the latest version. Thanks

**Comment by manikavi** [comment]
@jzhw0130 , 
  I'm using `compile files('libs/iHealthLibrary_2.3.0.26_log.jar') ` in build.gradle

**Comment by jzhw0130** [comment]
@manikavi 

Download the jar with the link above, replace your jar, then try again

**Comment by manikavi** [comment]
@jzhw0130 ,

           updated to latest jar,only once i got this below log,startmeasure() is not called,Please help me to handle this action.

```
 action: communicate_timeout
10-07 19:52:41.489 15649-15649/com.bg5.app I/Bg5Demo: message: {"communicate_timeout_id":45}
```

**Comment by qqskim** [comment]
The action communicate_timeout      means send command failed, you have to call the Api again.

communicate_timeout_id means which api do you call.  45 means setBottleMessage


Could you send me your latest code for BG5Demo.java?

**Comment by manikavi** [comment]
@qqskim ,

Please Check here

[https://gist.github.com/manikavi/eb714f7d2b55d579fb34c0921b05b648](url)

**Comment by jzhw0130** [comment]
@manikavi 

I have read your code, it is ok now.
For the 'communicate_timeout' problem, could you send me logs when the problem occurs again?

Thanks
