### ISSUE TITLE
Automatically connect with ihealth device if Bluetooth is ON

### ISSUE THREAD

**Issue by manikavi** [iHealthDeviceLabs/iHealthDeviceLabs-Android#33]
Hi,
   I need  to clarify my doubt,

**Automatically connect with ihealth device if Bluetooth is ON.**

_In android code, I can use *_Background Service\* for this,before doing i want to make sure whether it is possible or not with ihealth lib?

**Comment by jzhw0130** [comment]
@manikavi 
Support

**Comment by manikavi** [comment]
@jzhw0130 , Could you please give me more details?

**Comment by qqskim** [comment]
Call the Api in background service as you do now.

**Comment by manikavi** [comment]
@jzhw0130 ,
@qqskim 

Please check  added code here ,

[https://gist.github.com/manikavi/04e7e924f911ea3a301fd12a5e38683b](url)

**Log :**
CallbackId is not getting in this log


```
10-12 10:17:11.141 2065-2065/com.cw.app I/iHealthService: Within IhealthService onStartCommand ...
10-12 10:17:11.141 2065-2065/com.cw.app I/iHealthService: Within IhealthService onStartCommand1 ...
10-12 10:17:11.143 2065-2065/com.cw.app I/iHealthService: Within IhealthService onStartCommand2 ...
10-12 10:17:11.143 2065-2065/com.cw.app I/iHealthService: Within IhealthService onStartCommand3 ...
10-12 10:17:11.146 2065-2065/com.cw.app I/iHealthService: Within IhealthService onStartCommand4 ...
10-12 10:17:11.164 2065-2065/com.cw.app I/iHealthService: Within IhealthService onStartCommand5 ...
10-12 10:17:11.164 2065-2065/com.cw.app I/iHealthService: Within IhealthService onStartCommand6 ...
10-12 10:17:11.165 2065-2065/com.cw.app I/iHealthService: Within IhealthService onStartCommand7 ...
```

**Comment by jzhw0130** [comment]
@manikavi 

For the link https://gist.github.com/manikavi/04e7e924f911ea3a301fd12a5e38683b

Get 404, page not found

**Comment by manikavi** [comment]
@jzhw0130,
  It is opening for me,could you please  copy paste this link?

**Comment by manikavi** [comment]
@jzhw0130 ,
   Are you able to open the file?

**Comment by jzhw0130** [comment]
@manikavi 

Not open now.

**Comment by manikavi** [comment]
Please check this

[ihealthservicee.txt](https://github.com/iHealthDeviceLabs/iHealthDeviceLabs-Android/files/532581/ihealthservicee.txt)

**Comment by manikavi** [comment]
@jzhw0130 , Did you check that ?

**Comment by qqskim** [comment]
iHealthDevicesManager.getInstance().init(IhealthService.this);

Change:

iHealthDevicesManager.getInstance().init(context);

**Comment by manikavi** [comment]
@qqskim ,  Thanks a lot, I forgot to change `IhealthService.this `to` context `in my previous code,now i made that change,I launched my app,taken offline reading,here **iHealthDevicesCallback** is not called. please check this log

[offline_when_bt_on.txt](https://github.com/iHealthDeviceLabs/iHealthDeviceLabs-Android/files/532936/offline_when_bt_on.txt)

**Comment by manikavi** [comment]
@qqskim, Are you there?

**Comment by manikavi** [comment]
@jzhw0130 ,
@qqskim , I think i have to write code for getting values from ihealth device inside Broadcastreceiver,Please correct me if im wrong?

**Comment by qqskim** [comment]
Hi


From the log, you have the callback for the Api  —   iHealthDevicesManager.getInstance().sdkUserInAuthor(context, userName, clientId, clientSecret, callbackId);

 I/iHealthService:   username:anudroid.apk@gmail.com - userstatus:2

After get the callback, call startDiscovery() .

Moreover, the link below is done for more details, you can take a place, then send update log, maybe we will get the problem.

http://pan.baidu.com/s/1eSJoYHW

Thanks

**Comment by manikavi** [comment]
@qqskim ,
 I already wrote that inside  ` if (mBluetoothAdapter != null) `condition.Please check

```
   @Override
    public int onStartCommand(Intent intent, int flags, int startId) {
        

        try{
       
            context = getApplicationContext();
        
            //get Local Bluetooth Adapter,return null if nothing found.
            mBluetoothAdapter = BluetoothAdapter.getDefaultAdapter();
            

        /*
		 * Initializes the iHealth devices manager. Can discovery available iHealth devices nearby
		 * and connect these devices through iHealthDevicesManager.
		 */
            iHealthDevicesManager.getInstance().init(context);
          
		/*
		 * Register callback to the manager. This method will return a callback Id.
		 */
            callbackId = iHealthDevicesManager.getInstance().registerClientCallback(iHealthDevicesCallback);
         
            Log.i(LOG_TAG , "callbackId  "+callbackId);

            //Check Certification Of ihealth Device
            iHealthDevicesManager.getInstance().sdkUserInAuthor(context, userName, clientId, clientSecret, callbackId);

            if (mBluetoothAdapter != null){
                Log.i(LOG_TAG, "mBluetoothAdapter != null");
                if (mBluetoothAdapter.isEnabled()){
                    if (spiceManager != null){
                        if (!spiceManager.isStarted()){
                            spiceManager.start(context);
                        }
                    }

                    ensureDiscoverable();

                    iHealthDevicesManager.getInstance().startDiscovery(iHealthDevicesManager.DISCOVERY_BG5
                            | iHealthDevicesManager.DISCOVERY_HS4S
                            | iHealthDevicesManager.DISCOVERY_BP5 | iHealthDevicesManager.DISCOVERY_PO3);

                }else {
                    Intent BT_Enable_Intent = new Intent(BluetoothAdapter.ACTION_REQUEST_ENABLE);
                    BT_Enable_Intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
                    context.startActivity(BT_Enable_Intent);
                }
            }else{
                stopSelf();
            }


        }
        catch (Exception e){
            e.printStackTrace();
        }

        return START_STICKY;
    }
```

**Comment by manikavi** [comment]
@qqskim ,
Please check this ,this are all from PO3 & BP5

[https://gist.github.com/manikavi/2a03aa4bb6af8e92665efd0750763999](url)

[https://gist.github.com/manikavi/b1aeb663719fca805ca6753ec2cbc939](url)

**Comment by manikavi** [comment]
@qqskim , You there?,Could you please check my logs

**Comment by manikavi** [comment]
Added final service code here for your reference,If possible shall we have meeting and discuss?

[oct_21.txt](https://github.com/iHealthDeviceLabs/iHealthDeviceLabs-Android/files/543827/oct_21.txt)

**Comment by jzhw0130** [comment]
@manikavi 

I cannot get the log from the link,  could you do as the oct_21.txt(Attach on github)? 
Or send the log to my email (jingzhiwei@ihealthlabs.com.cn)

thanks

**Comment by manikavi** [comment]
Sure @jzhw0130

**Comment by manikavi** [comment]
@jzhw0130 ,
@qqskim ,

 Please Make sure about this things


 In ihealth we have three things sir 

1.OnLine - BT is On,Manually do all process,(Both ihealth device and Android Phone we need )
2.Offline - BT is OFF,now patient dont have andorid phone,only ihealth devices he is having.I taken measurement,On next successfully OnLine measurement all history details will push to DB

Code for above two points is done

3.Automatically connect with ihealth device if Bluetooth is ON -

           3.1.sometimes onScanDevice() is not called,
           3.2.HANDLER_DEVICE_STATE_CONNECTIONFAIL getting this message

I.m really need your help for doing Point 3.I have send code also .Please help me to work on this?



----------------------

**Comment by qqskim** [comment]
For case 1, case 2, do you call the sdk api on activity, not on service? 

For case 3, you call the idk api on  service.  It   always does not work, or sometimes work,  sometimes does not work?


I’m downloading your demo, it is very slow..  Because I have to visit google with VPN.

Could you send me the demo by email or other ways?

Thanks


jing
