### ISSUE TITLE
HS4 return empty manufacturer data

### ISSUE THREAD

**Issue by ivl** [iHealthDeviceLabs/iHealthDeviceLabs-Android#34]
HS4 return empty manufacturer data
        public void onDeviceConnectionStateChange(String mac, String deviceType, int status, int errorID, Map manufactorData) 

Always return nil manufactorData. We need such info like firmware version, hardware version etc as it was for iOS library.

**Comment by qqskim** [comment]
Hi

**Comment by jzhw0130** [comment]
<img width="481" alt="88e72599-2509-43ac-9745-de482e218fd1" src="https://cloud.githubusercontent.com/assets/12521790/19750863/7be13ef4-9c27-11e6-898c-fa877b246a7c.png">

**Comment by ivl** [comment]
Thanks
