### ISSUE TITLE
HS4S action : error_hs (700)

### ISSUE THREAD

**Issue by 4ctarus** [iHealthDeviceLabs/iHealthDeviceLabs-Android#35]
Hello,

When i try to disconnect from my scale (hs4s), the ihealthdevicecallback return me 
type:HS4S
action:error_hs
message:{"error":700}

what does it mean?

(v 2.2.9)
ty.

**Comment by qqskim** [comment]
Hi

Did you call disconnect() when hs4s is measuring?

**Comment by jzhw0130** [comment]
Hi

Please update the latest version (2.3.2) which fix the problem.
Thanks
