### ISSUE TITLE
java.lang.NullPointerException: Attempt to get length of null array

### ISSUE THREAD

**Issue by BilalSiddiqui** [iHealthDeviceLabs/iHealthDeviceLabs-Android#36]
We are integrating iHealth HS4 device and its crashing on Nexus 5,9(MarshMallow).
Crashing on the line.
         iHealthDevicesManager.getInstance().init(getActivity());

Crash Log:
 E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: com.gazuntite.patient, PID: 4956
                                                                     java.lang.RuntimeException: Error receiving broadcast Intent { act=android.bluetooth.adapter.action.STATE_CHANGED flg=0x4000010 (has extras) } in com.gazuntite.patient.assesmentplans.plans.WeightEntryFragment$3@8906ccb
                                                                         at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:891)
                                                                         at android.os.Handler.handleCallback(Handler.java:739)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:148)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                      Caused by: java.lang.NullPointerException: Attempt to get length of null array
                                                                         at com.ihealth.communication.utils.Logger.a(Unknown Source)
                                                                         at com.ihealth.communication.utils.Logger.a(Unknown Source)
                                                                         at com.ihealth.communication.utils.Logger.w(Unknown Source)
                                                                         at com.ihealth.communication.utils.Log.w(Unknown Source)
                                                                         at com.ihealth.communication.manager.iHealthDevicesManager.init(Unknown Source)
                                                                         at com.gazuntite.patient.assesmentplans.plans.WeightEntryFragment.initIHealth(WeightEntryFragment.java:423)
                                                                         at com.gazuntite.patient.assesmentplans.plans.WeightEntryFragment.access$1300(WeightEntryFragment.java:55)
                                                                         at com.gazuntite.patient.assesmentplans.plans.WeightEntryFragment$3.onReceive(WeightEntryFragment.java:658)
                                                                         at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:881)
                                                                         at android.os.Handler.handleCallback(Handler.java:739) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                         at android.os.Looper.loop(Looper.java:148) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by BilalSiddiqui** [comment]
After handle this exception i am unable to connect the device.

**Comment by jzhw0130** [comment]
@BilalSiddiqui 

Please do a test with iHealth demo with your phone , make sure demo works well or not.

**Comment by jzhw0130** [comment]
Moreover, please try the beta version.

[iHealthLibrary_2.3.1.4.jar.zip](https://github.com/iHealthDeviceLabs/iHealthDeviceLabs-Android/files/601474/iHealthLibrary_2.3.1.4.jar.zip)

**Comment by BilalSiddiqui** [comment]
@jzhw0130 

We have tested your demo but it crashed!
After that we have tried your provided beta version 2.3.1.4.jar.Now its not crashing on both devices(Nexus9,nexus5) and working fine on nexus 5 with BP5 and HS4.On Nexus 9 its not able to connect the device HS4 but working fine with BP5.

Error Message on Nexus 9 with HS4:com.gazuntite.patient E/**Runtime_iHealthDM: Not found service**

Complete Log for Help:
11-21 11:21:37.668 19952-19952/com.gazuntite.patient D/WeightEntryFragment: checkBluetoothPermission: isPermitted: true
11-21 11:21:37.669 19952-19952/com.gazuntite.patient D/WeightEntryFragment: startDiscovery: discoveryType: 16
11-21 11:21:37.670 19952-19952/com.gazuntite.patient D/BluetoothAdapter: startLeScan(): null
11-21 11:21:37.672 19952-19952/com.gazuntite.patient D/BluetoothAdapter: STATE_ON
11-21 11:21:37.686 19952-19965/com.gazuntite.patient D/BluetoothLeScanner: onClientRegistered() - status=0 clientIf=5 mClientIf=0
11-21 11:21:37.830 19952-19952/com.gazuntite.patient D/WeightEntryFragment: onScanDevice: mac:9059AF24014A, deviceType:HS4, rssi:-64, manufactorData:{}
11-21 11:21:37.846 19952-19952/com.gazuntite.patient D/WeightEntryFragment: handleMessage::HANDLER_SCAN: Device scanned: mScannedDeviceMac: 9059AF24014A, mScannedDeviceType: HS4
11-21 11:21:37.865 19952-19952/com.gazuntite.patient I/WeightEntryFragment: handleMessage::HANDLER_SCAN: Now connecting...
11-21 11:21:37.865 19952-19952/com.gazuntite.patient D/WeightEntryFragment: connectToDevice: mac: 9059AF24014A, type: HS4
11-21 11:21:37.885 19952-19952/com.gazuntite.patient D/BluetoothAdapter: stopLeScan()
11-21 11:21:37.887 19952-19952/com.gazuntite.patient D/BluetoothAdapter: STATE_ON
11-21 11:21:37.892 19952-19952/com.gazuntite.patient D/BluetoothGatt: connect() - device: 90:59:AF:24:01:4A, auto: false
11-21 11:21:37.892 19952-19952/com.gazuntite.patient D/BluetoothGatt: registerApp()
11-21 11:21:37.892 19952-19952/com.gazuntite.patient D/BluetoothGatt: registerApp() - UUID=b1b39edf-febd-4bd7-8754-0998792dc3e1
11-21 11:21:37.894 19952-20298/com.gazuntite.patient D/BluetoothGatt: onClientRegistered() - status=0 clientIf=5
11-21 11:21:37.995 19952-19952/com.gazuntite.patient D/WeightEntryFragment: onDeviceConnectionStateChange: mac:9059AF24014A, deviceType:HS4, status:0, errorid:0, manufactorData:null
11-21 11:21:38.007 19952-19966/com.gazuntite.patient D/BluetoothGatt: onClientConnectionState() - status=0 clientIf=5 device=90:59:AF:24:01:4A
11-21 11:21:38.308 19952-19966/com.gazuntite.patient D/BluetoothGatt: discoverServices() - device: 90:59:AF:24:01:4A
11-21 11:21:38.310 19952-20535/com.gazuntite.patient D/BluetoothGatt: onSearchComplete() = Device=90:59:AF:24:01:4A Status=0
**11-21 11:21:38.314 19952-20535/com.gazuntite.patient E/Runtime_iHealthDM: Not found service**
11-21 11:22:21.446 19952-19966/com.gazuntite.patient D/BluetoothGatt: onClientConnectionState() - status=19 clientIf=5 device=90:59:AF:24:01:4A
11-21 11:22:21.946 19952-19966/com.gazuntite.patient D/BluetoothGatt: cancelOpen() - device: 90:59:AF:24:01:4A
11-21 11:22:21.948 19952-19966/com.gazuntite.patient D/BluetoothGatt: close()
11-21 11:22:21.948 19952-19966/com.gazuntite.patient D/BluetoothGatt: unregisterApp() - mClientIf=5
11-21 11:22:22.057 19952-19952/com.gazuntite.patient D/WeightEntryFragment: onDeviceConnectionStateChange: mac:9059AF24014A, deviceType:HS4, status:3, errorid:19, manufactorData:null
11-21 11:22:22.075 19952-19952/com.gazuntite.patient D/WeightEntryFragment: handleMessage::HANDLER_DISCONNECT: Devices disconnected: mac: 9059AF24014A, type: HS4

**Comment by jzhw0130** [comment]
@BilalSiddiqui 

Hi, we add more  log to get the problem on Nexus9 with HS4. Please try and upload the log, thanks


[iHealthLibrary_2.3.1.4_log.jar.zip](https://github.com/iHealthDeviceLabs/iHealthDeviceLabs-Android/files/602920/iHealthLibrary_2.3.1.4_log.jar.zip)

**Comment by BilalSiddiqui** [comment]
@jzhw0130 here is error and complete log.

**Error Message : 

11-21 17:38:16.879 8094-8107/com.gazuntite.patient E/Runtime_ble: GattService:00001800-0000-1000-8000-00805f9b34fb
11-21 17:38:16.885 8094-8107/com.gazuntite.patient E/Runtime_iHealthDM: onServicesDiscovered:[00001800-0000-1000-8000-00805f9b34fb]
11-21 17:38:16.889 8094-8107/com.gazuntite.patient E/Runtime_iHealthDM: Not found service**

Complete Log: 

11-21 17:33:53.411 2740-2740/com.gazuntite.patient D/WeightEntryFragment: checkBluetoothPermission: isPermitted: true
11-21 17:33:53.411 2740-2740/com.gazuntite.patient D/WeightEntryFragment: initIHealth
11-21 17:33:53.411 2740-2740/com.gazuntite.patient I/Runtime_iHealthDM: init()
11-21 17:33:53.414 2740-2740/com.gazuntite.patient W/Runtime_iHealthDM: iHealthLibrary Version:ASDK_2.3.1.4
11-21 17:33:53.417 2740-2740/com.gazuntite.patient V/Runtime_iHealthDM: handlerthread has existed
11-21 17:33:53.419 2740-2740/com.gazuntite.patient V/Runtime_iHealthDM: mHandler has existed
11-21 17:33:53.420 2740-2740/com.gazuntite.patient I/Runtime_iHealthDM: registerClientCallback(com.gazuntite.patient.assesmentplans.plans.WeightEntryFragment$2@4b2e4a8)
11-21 17:33:53.420 2740-2740/com.gazuntite.patient I/Runtime_iHealthDM: addCallbackFilterForDeviceType(1, [Ljava.lang.String;@3c6bbc1)
11-21 17:33:53.421 2740-2740/com.gazuntite.patient I/Runtime_iHealthDM: sdkUserInAuthor(com.gazuntite.patient.main.MainActivity@46374c5, sheraz.nadeem@gazuntite.com, f5d966b564544d72a5c6ed193a71d53e, d39cb540df4f4bfba2d3a8b8125c635a, 1)
                                                                        
                                                                        --------- beginning of system
11-21 17:33:53.426 2740-3992/com.gazuntite.patient D/WeightEntryFragment: onUserStatus: username: sheraz.nadeem@gazuntite.com, userStatus: 2
11-21 17:33:53.427 2740-3993/com.gazuntite.patient V/a: already exist AppID :: b14f049526a08438
11-21 17:33:53.430 2740-3993/com.gazuntite.patient V/a: already exist DeviceID :: ffffffff-9dce-2ffa-0000-0000587c41b9
11-21 17:33:53.472 2740-2740/com.gazuntite.patient V/Runtime_iHealthDM: network name：WIFI
11-21 17:33:53.473 2740-2740/com.gazuntite.patient D/WeightEntryFragment: handleMessage::HANDLER_USER_STATUS: username: sheraz.nadeem@gazuntite.com, userStatus: 2
11-21 17:33:53.473 2740-2740/com.gazuntite.patient D/WeightEntryFragment: checkBluetoothPermission: isPermitted: true
11-21 17:33:53.474 2740-2740/com.gazuntite.patient D/WeightEntryFragment: startDiscovery: discoveryType: 16
11-21 17:33:53.474 2740-2740/com.gazuntite.patient I/Runtime_iHealthDM: startDiscovery(10)
11-21 17:33:53.478 2740-2740/com.gazuntite.patient V/Runtime_ble: scan(true)
11-21 17:33:53.480 2740-2740/com.gazuntite.patient D/BluetoothAdapter: startLeScan(): null
11-21 17:33:53.481 2740-2740/com.gazuntite.patient D/BluetoothAdapter: STATE_ON
11-21 17:33:53.481 2740-3993/com.gazuntite.patient I/SSLCustomSocketFactory: fnfidscertificate.p12 (No such file or directory)
11-21 17:33:53.483 2740-2753/com.gazuntite.patient D/BluetoothLeScanner: onClientRegistered() - status=0 clientIf=5 mClientIf=0
11-21 17:33:53.489 2740-3993/com.gazuntite.patient V/HttpsPost: Post   https://api.ihealthlabs.com:443/api5/UserSign.htm 
                                                                PhoneName=Nexus+9&client_id=f5d966b564544d72a5c6ed193a71d53e&PhoneOS=android7.0&hash=e813b69c287f0c5a7f3fb26c66c6f7f2&client_secret=d39cb540df4f4bfba2d3a8b8125c635a&PhoneID=ffffffff-9dce-2ffa-0000-0000587c41b9&PhoneRegion=US&sv=b3118e4fa5204f6dba1e2f1723270747&Token=&username=sheraz.nadeem%40gazuntite.com&PhoneLanguage=en&AppVersion=ASDK_2.3.1.4&AppGuid=b14f049526a08438&sc=7c789858c0ec4ebf8189ebb14b6730a5&QueueNum=111111
11-21 17:33:53.591 2740-2740/com.gazuntite.patient W/IInputConnectionWrapper: finishComposingText on inactive InputConnection
11-21 17:33:53.632 2740-2740/com.gazuntite.patient I/Runtime_iHealthDM: onScanDevice(9059AF24014A, HS4, -76, {})
11-21 17:33:53.634 2740-2740/com.gazuntite.patient D/WeightEntryFragment: onScanDevice: mac:9059AF24014A, deviceType:HS4, rssi:-76, manufactorData:{}
11-21 17:33:53.646 2740-2740/com.gazuntite.patient D/WeightEntryFragment: handleMessage::HANDLER_SCAN: Device scanned: mScannedDeviceMac: 9059AF24014A, mScannedDeviceType: HS4
11-21 17:33:53.654 2740-2740/com.gazuntite.patient I/WeightEntryFragment: handleMessage::HANDLER_SCAN: Now connecting...
11-21 17:33:53.654 2740-2740/com.gazuntite.patient D/WeightEntryFragment: connectToDevice: mac: 9059AF24014A, type: HS4
11-21 17:33:53.654 2740-2740/com.gazuntite.patient I/Runtime_iHealthDM: connectDevice(sheraz.nadeem@gazuntite.com, 9059AF24014A)
11-21 17:33:53.655 2740-2740/com.gazuntite.patient I/Runtime_iHealthDM: stopDiscovery()
11-21 17:33:53.662 2740-2740/com.gazuntite.patient V/Runtime_ble: scan(false)
11-21 17:33:53.670 2740-2740/com.gazuntite.patient D/BluetoothAdapter: stopLeScan()
11-21 17:33:53.671 2740-2740/com.gazuntite.patient D/BluetoothAdapter: STATE_ON
11-21 17:33:53.673 2740-2740/com.gazuntite.patient V/Runtime_ble: connectDevice(90:59:AF:24:01:4A, android.bluetooth.BluetoothAdapter@4dd2d78)
11-21 17:33:53.676 2740-2740/com.gazuntite.patient D/BluetoothGatt: connect() - device: 90:59:AF:24:01:4A, auto: false
11-21 17:33:53.676 2740-2740/com.gazuntite.patient D/BluetoothGatt: registerApp()
11-21 17:33:53.676 2740-2740/com.gazuntite.patient D/BluetoothGatt: registerApp() - UUID=55ddd89c-3026-4b6b-8b03-348216031c85
11-21 17:33:53.677 2740-2841/com.gazuntite.patient D/BluetoothGatt: onClientRegistered() - status=0 clientIf=5
11-21 17:33:53.680 2740-2740/com.gazuntite.patient V/Runtime_iHealthDM: connection result: true
11-21 17:33:53.692 2740-2740/com.gazuntite.patient I/Runtime_iHealthDM: onScanFinish()
11-21 17:33:53.782 2740-2740/com.gazuntite.patient I/Runtime_iHealthDM: onDeviceConnectionStateChange(9059AF24014A, HS4, 0, 0)
11-21 17:33:53.784 2740-2740/com.gazuntite.patient D/WeightEntryFragment: onDeviceConnectionStateChange: mac:9059AF24014A, deviceType:HS4, status:0, errorid:0, manufactorData:null
11-21 17:33:53.807 2740-2753/com.gazuntite.patient D/BluetoothGatt: onClientConnectionState() - status=0 clientIf=5 device=90:59:AF:24:01:4A
11-21 17:33:53.807 2740-2753/com.gazuntite.patient V/Runtime_ble: onConnectionStateChange(9059AF24014A, 0, 2)
11-21 17:33:53.808 2740-2753/com.gazuntite.patient V/Runtime_ble: Connection Success
11-21 17:33:53.809 2740-2753/com.gazuntite.patient V/Runtime_iHealthDM: onConnectionStateChange(9059AF24014A, 0, 2)
11-21 17:33:54.110 2740-2753/com.gazuntite.patient D/BluetoothGatt: discoverServices() - device: 90:59:AF:24:01:4A
11-21 17:33:54.113 2740-2752/com.gazuntite.patient D/BluetoothGatt: onSearchComplete() = Device=90:59:AF:24:01:4A Status=0
11-21 17:33:54.113 2740-2752/com.gazuntite.patient V/Runtime_ble: onServicesDiscovered(1)
11-21 17:33:54.119 2740-2752/com.gazuntite.patient E/Runtime_ble: GattService:00001800-0000-1000-8000-00805f9b34fb
11-21 17:33:54.122 2740-2752/com.gazuntite.patient E/Runtime_iHealthDM: onServicesDiscovered:[00001800-0000-1000-8000-00805f9b34fb]
11-21 17:33:54.124 2740-2752/com.gazuntite.patient E/Runtime_iHealthDM: Not found service
11-21 17:33:55.768 2740-3993/com.gazuntite.patient V/HttpsPost: Post result -->{"QueueNum":111111,"Result":"1","ResultMessage":"100","ReturnValue":{"APIName":"OpenApiActivity OpenApiBG OpenApiBP OpenApiFood OpenApiSleep OpenApiSpO2 OpenApiSport OpenApiUserInfo OpenApiWeight","AccessToken":"NfhI80ZdMOiKIIn4UdzESkTTp6OL7v-jyjdnGoRbvRPuB5K8TcFZ5hlQVnAyemc6BrljS65ZodsTLEIf2bI5bn1f4wlqNANFASxgunA3d7HxU27yJcLl2WacxbVin-jEBhRogixJh1f990zblT8uTaKFPQFmMERC5OSwh1S4DGaJzpeHjTHHy355Vzz*f14FcLispaGpecIICLzJ0lW5KttNnwGWXmnbJiYyr5rgp1w","Expires":1482582835,"ID":1718566,"RefreshToken":"1VUT08i0l8wYiErQdt1iDYwUYVG2x3UcxFscCXILUpszgTN8TH9RTRlSa-*dY8Ift59vpffjvVjFdr9RVaKtNlkDkezye6LoR*b--SgtWmxk7w5Zqep8XuvaTCyfAKk9I1O1reEJB*GZUhQYsmJCBk8jDMTA5zcDHp1t8cLc-KRCoTZQ2WITGZ-0nnXpWBAPw25RKTZgfTbl4K0xO8tcLeHVjC0pIb-3CQRzw3-zzvQ","RegionHost":"https:\/\/api.ihealthlabs.com:8443"},"TS":1479731635}
11-21 17:34:37.389 2740-2753/com.gazuntite.patient D/BluetoothGatt: onClientConnectionState() - status=19 clientIf=5 device=90:59:AF:24:01:4A
11-21 17:34:37.389 2740-2753/com.gazuntite.patient V/Runtime_ble: onConnectionStateChange(9059AF24014A, 19, 0)
11-21 17:34:37.390 2740-2753/com.gazuntite.patient V/Runtime_ble: DisConnection Success
11-21 17:34:37.892 2740-2753/com.gazuntite.patient D/BluetoothGatt: cancelOpen() - device: 90:59:AF:24:01:4A
11-21 17:34:37.894 2740-2753/com.gazuntite.patient D/BluetoothGatt: close()
11-21 17:34:37.894 2740-2753/com.gazuntite.patient D/BluetoothGatt: unregisterApp() - mClientIf=5
11-21 17:34:37.895 2740-2753/com.gazuntite.patient V/Runtime_iHealthDM: onConnectionStateChange(9059AF24014A, 19, 0)
11-21 17:34:37.896 2740-2753/com.gazuntite.patient V/Runtime_iHealthDM: removeDevice(9059AF24014A, HS4)
11-21 17:34:38.012 2740-2740/com.gazuntite.patient I/Runtime_iHealthDM: onDeviceConnectionStateChange(9059AF24014A, HS4, 3, 19)
11-21 17:34:38.016 2740-2740/com.gazuntite.patient D/WeightEntryFragment: onDeviceConnectionStateChange: mac:9059AF24014A, deviceType:HS4, status:3, errorid:19, manufactorData:null
11-21 17:34:38.028 2740-2740/com.gazuntite.patient D/WeightEntryFragment: handleMessage::HANDLER_DISCONNECT: Devices disconnected: mac: 9059AF24014A, type: HS4

**Comment by qqskim** [comment]
Hi

The os version of your Nexus 9 is 7.0(Nougat)??

If yes, you have to update the os version to 7.1, because there is a bug on 7.0,  can not connect device with bluetooth low energy.

**Comment by BilalSiddiqui** [comment]
Hi @qqskim 

Yes, Nexus 9 is on Nougat 7.0.It means we have to wait for 7.1 update on nexus 9 to work on HS4.
But its working fine with BP5.

Please let me know if you found any work around to that issue.

Thanks for your Support

**Comment by qqskim** [comment]
Yes

Because BP5 work with bluetooth 3.0, HS4 work with bluetooth low energy(4.0).
The bug exists only for bluetooth low energy.
