### ISSUE TITLE
Scan,Connect,Get Values from  ihealth device without using iHealthDevicesCallback 

### ISSUE THREAD

**Issue by manikavi** [iHealthDeviceLabs/iHealthDeviceLabs-Android#38]
Hi,
   Is it Possible to do below points with out using iHealth Library?

1.Scan ihealth devices
2.Connect ihealth devices
3.Get values from ihealth devices
4.Disconnect ihealth devices

**Comment by qqskim** [comment]
Sorry

It is impossible to do the work without iHealthLibrary now.  

Could you say more details about your needs? I will send to our product manager.



jing
