### ISSUE TITLE
iHealthLibrary_2.2.8.jar file is Corrupted in SDK 2.0 file

### ISSUE THREAD

**Issue by manikavi** [iHealthDeviceLabs/iHealthDeviceLabs-Android#4]
Hi,
   imported  SDK 2.0 file ,started testing with **BP5 08B6E5**,once i click on iHealthLibrary_2.2.8.jar,Im getting "CORRUPTED" message.find screenshot here.

![image](https://cloud.githubusercontent.com/assets/6669647/16088012/c6137422-3342-11e6-9700-39b96515132b.png)

**Comment by jzhw0130** [comment]
@manikavi 
Hi, did you try our demo with BP5?
Moreover, why did you try to open iHealthLibrary_2.2.8.jar?

**Comment by manikavi** [comment]
Hi,
   i got BP5 control instance as null,for  understanding and resolving this error,i tried to open iHealthLibrary_2.2.8.jar,that time i got this,So I posted..Please check my first reply for Issue3 for more info

[https://github.com/iHealthDeviceLabs/iHealthDeviceLabs-Android/issues/3](url)
