### ISSUE TITLE
BG5: Update usenum value in getBottleMessage()

### ISSUE THREAD

**Issue by inggaa** [iHealthDeviceLabs/iHealthDeviceLabs-Android#41]
In the ACTION_GET_INFO, I keep on getting ` {"usenum":0,"expiretime":"2016-02-14"}`. How can I update the usenum value?

**Comment by jzhw0130** [comment]
@inggaa 

Hi

Could you send more logs from Logcat?

thanks


Jing

**Comment by jzhw0130** [comment]
Hi

    /**
     * The strip used num, from offline data by Bg5 device.
     */
    public static final String GET_USENUM = "usenum";

If you only do the measurement online(BG5 connected with your App), usenum is always zero.

The value of usenum only count the measurement offline (BG5 not connected with your app).

**Comment by inggaa** [comment]
Thanks
