### ISSUE TITLE
How to set the time on the device via the framework?

### ISSUE THREAD

**Issue by klaszlo8207** [iHealthDeviceLabs/iHealthDeviceLabs-Android#43]
I have a BP550BT Track device, how can I set the time after device connected?

**Comment by qqskim** [comment]
/**
 * Synchronize the system time to BP device and get function of device
 * <ul>
 * <li>
 * This is an asynchronous call, it will return immediately.
 * </li>
 * <li>
 * If operation successfully. following callback will be triggered: <br/>
 * {@link iHealthDevicesCallback#onDeviceNotify(String mac, String deviceType, String action, String message)} <br/>
 * <ul>
 * <li>
 * The <b>action</b> is {@link BpProfile#ACTION_FUNCTION_INFORMATION_BP}
 * </li>
 * <li>
 * The keys of the <b>message</b> will show in {@link BpProfile#ACTION_FUNCTION_INFORMATION_BP keyList of the action}.
 * </li>
 * </ul>
 * </li>
 * <li>
 * If error happens, following callback will be triggered: <br/>
 * {@link iHealthDevicesCallback#onDeviceNotify(String mac, String deviceType, String action, String message)}<br/>
 * <ul>
 * <li>
 * The <b>action</b> is {@link BpProfile#ACTION_ERROR_BP}.
 * </li>
 * <li>
 * The <b>message</b> will be a JSON string with error ID and description,<br/>
 * the keys will show in the {@linkplain BpProfile#ACTION_ERROR_BP KeyList of the action}.
 * </li>
 * </ul>
 * </li>
 * <li>
 * Attention, it is mandatory to call following method before you call this method:<br/>
 * {@link iHealthDevicesManager#registerClientCallback(iHealthDevicesCallback)}
 * </li>
 * <p>
 * </ul>
 */
public void getFunctionInfo()

**Comment by klaszlo8207** [comment]
thanks
