### ISSUE TITLE
Is it free?

### ISSUE THREAD

**Issue by klaszlo8207** [iHealthDeviceLabs/iHealthDeviceLabs-Android#44]
This library is free? Can I use this in free or commercial products?

**Comment by qqskim** [comment]
Hi

The library is free now, but you have to register your application as follows: https://github.com/iHealthDeviceLabs/iHealthDeviceLabs-Android/blob/master/doc/Developer_Registration_Application_Instruction.md <https://github.com/iHealthDeviceLabs/iHealthDeviceLabs-Android/blob/master/doc/Developer_Registration_Application_Instruction.md>

Jing
