### ISSUE TITLE
ConnectDevice(Unknown Source) error

### ISSUE THREAD

**Issue by klaszlo8207** [iHealthDeviceLabs/iHealthDeviceLabs-Android#45]
When I connect to a device from your example, it is working good, but when I copy paste the libs to a new android project and then startdiscovery and then in 

case HANDLER_SCAN:

want to connect with

                    iHealthDevicesManager.getInstance().stopDiscovery();
                    iHealthDevicesManager.getInstance().connectDevice("", mac_scan, type_scan);

I get this:

E/UncaughtException: java.lang.NullPointerException
                                                                             at com.ihealth.communication.manager.iHealthDevicesManager.connectDevice(Unknown Source)

What is the probleme here?

**Comment by qqskim** [comment]
Hi


You have to do as follows:  https://github.com/iHealthDeviceLabs/iHealthDeviceLabs-Android/blob/master/README.md <https://github.com/iHealthDeviceLabs/iHealthDeviceLabs-Android/blob/master/README.md>

Step 4 is missed now.


Jing

**Comment by klaszlo8207** [comment]
qqskim thanks, almost done, I registered an app, and now it is in state: not audit
So I think it will be usable after you guys add a permission to it, not?
Now when I connect I get a connect state3, and I get a user with a mail onUserStatis and usertatus 5
The connection not working again, it says disconnecting from service.

**Comment by qqskim** [comment]
If User Status is 5 or 6 or 7 or 8, connect will fail.
Your application will be usable after be authorized.  
Could you tell me your clientID or userAccount?

**Comment by klaszlo8207** [comment]
clientid is 070977633d3747a7b9761f2a17b1cb0f
I need to use  for blood pressure

but always get status 5 and with connect state 3 (fail)
the username is my user mail or my app name, or what?

**Comment by klaszlo8207** [comment]
Oh and I need to 550BT bp connection

**Comment by jzhw0130** [comment]
@klaszlo8207 

Impossible now.
Maybe you can contact our business manager Louie LYU <louie@ihealthlabs.com> for more help.

**Comment by jzhw0130** [comment]
@klaszlo8207 

username is user email.

**Comment by klaszlo8207** [comment]
Can you give me a skype or mail? Because we got always an userstatus with 5 after auth. Thanks

**Comment by jzhw0130** [comment]
@klaszlo8207 

Contact our business manager Louie LYU (louie@ihealthlabs.com) for more help.

**Comment by soshial** [comment]
How do I change user status? SDK example works okay, but when I copied `BP5.java` and `MainActivity.java`, it crashes: 

    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.ihealth.communication.cloudmanager.iHealthDeviceCloudManager.getDevicePermisson(java.lang.String, java.lang.String)' on a null object reference
    at com.ihealth.communication.manager.iHealthDevicesManager.connectDevice(Unknown Source)
    at _______.view.MainActivity$3.onItemClick(MainActivity.java:228)

**Comment by jzhw0130** [comment]
@soshial 

Register the application:
https://github.com/iHealthDeviceLabs/iHealthDeviceLabs-Android/blob/master/doc/Developer_Registration_Application_Instruction.md

Call the authen api: (Step 4 on 'How to use  the iHealth SDK')
iHealthDevicesManager.getInstance().sdkUserInAuthor(MainActivity.this, userName, clientId, clientSecret, callbackId);
If verify success, all the api avaliable, else 10 trial days you will get.

**Comment by soshial** [comment]
Okay, I will register it. BUT WHY your example doesn't crash then?? It also has empty `userName`, `clientId`, `clientSecret`!

Also, is the crash really a normal behaviour for any SDK, when the app is simply not registered?
