### ISSUE TITLE
Nexus 5X  Android 6.0.1 can't discover HS4.

### ISSUE THREAD

**Issue by ivl** [iHealthDeviceLabs/iHealthDeviceLabs-Android#47]
Nexus 5X  Android 6.0.1 can't discover.
Log
I/Runtime_iHealthDM: startDiscovery(10)
V/Runtime_ble: scan(true)
D/BluetoothAdapter: startLeScan(): null
D/BluetoothAdapter: STATE_ON
D/BluetoothLeScanner: onClientRegistered() - status=0 clientIf=5
V/Runtime_ble: scan(false)
D/BluetoothAdapter: stopLeScan()
D/BluetoothAdapter: STATE_ON
I/Runtime_iHealthDM: onScanFinish()

Interesting detail. It could be observed if gluco BG5 also is discovering

**Comment by ivl** [comment]
Update: if to set target SDK 22 it works. But if any other value - not.
We need at least 25. Can you help us?

**Comment by qqskim** [comment]
Hi

Please add the location permission (AndroidManifest.xml)

<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />

**Comment by jzhw0130** [comment]
And

<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>

**Comment by jzhw0130** [comment]
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"

**Comment by ivl** [comment]
@jzhw0130 You demo application is not working. If to set SDK target to 25 level. As it is  in our application. It worked before. Not working now.

**Comment by ivl** [comment]
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" and <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" /> already added. I am not beginner with you SDK

**Comment by qqskim** [comment]
If set SDK target to 22 level, it works.  If not 22 level, it does not work??

Moreover, did you discover all iHealth devices together,  as :
iHealthDevicesManager.getInstance().startDiscovery(iHealthDevicesManager.DISCOVERY_BG5|iHealthDevicesManager.DISCOVERY_HS4);
Could you try to discover HS4 only?  as :

 iHealthDevicesManager.getInstance().startDiscovery(iHealthDevicesManager.DISCOVERY_HS4);

**Comment by ivl** [comment]
Only HS4 is not working. It works only in pair with BG5. We noticed this after upgrading to new version of your SDK. After long debugging session we found that if to try to discover HS4 - its not working at all. But Bg5 can be observed and in pair with BG5 HS4 also can be discovered. We thought that it somehow related that we are running it on background service. But later when we created empty application from beginning based on your example (line were added line by line from you demo) - it also not worked. Only when we changed targetSdkVersion 22 on gradle file as in your example  - it started to work without any problems as it was before. I am supposing its related to some deprecated function that you are  using. And probably if to use lower idk its not raise exception.

**Comment by ivl** [comment]
Please note that it affects only users of Nexus 5X Android 6.0.1. All other devices with other android versions are working well. But due Nexus 5X Android 6.0.1 our main target we need you fix this

**Comment by qqskim** [comment]
Please conform more details, thanks 
Question 1: The other phones which works well is 6.0+,  or Below 6.0? 
Question 2: Which other iHealth devices works well with your Nexus 5X?  HS4 use bluetooth low energy, BG5 use bluetooth 3.0.
Question 3: Did you mean the problem occur after update iHealth SDK(V2.3.2) ? The version before works well? 
Question 4: Our sdk demo(api level 25) does not work with HS4 on your Nexus 5X , but demo(api level 22) works well with HS4 on your Nexus 5X?

**Comment by ivl** [comment]
1. We have one android 7 that works well. We have several phones like samsung s5 s6 that use 6 android - works well. Issue only with Nexus 5X
2. Nexus 5X works well only with BG5. AM3S is not observable also like HS4. We have only this set of devices.
3. Exactly. Problem only in newest SDK 2.3.2. But we need new SDK because it solves other our issues.
4. Exactly. Your demo applications if to modify gradle to sdk target 24 or 25 stops working. But if to use 22 it works well (as our application also with 22 level but we need at least 24. We temporary use 22. But its not good for us).

**Comment by qqskim** [comment]
Thanks for your information.

Could you do a test with the condition, then send me the log from Logcat. 
1. SDK demo(android level 22), AM3S, Nexus 5x(6.0.1), Log Jar(https://github.com/iHealthDeviceLabs/iHealthDeviceLabs-Android/blob/master/lib/iHealthLibrary_2.3.2log.jar)
2. SDK demo(android level 25), AM3S, Nexus 5x(6.0.1), Log Jar(https://github.com/iHealthDeviceLabs/iHealthDeviceLabs-Android/blob/master/lib/iHealthLibrary_2.3.2log.jar)


We do s test with the condition:
1. SDK demo(android level 25), AM3S, Nexus 5(6.0.1), Log Jar(https://github.com/iHealthDeviceLabs/iHealthDeviceLabs-Android/blob/master/lib/iHealthLibrary_2.3.2log.jar)

Demo works well, Log as follows:
02-20 10:48:44.110 10861-10861/? E/MainActivity: Model:Nexus 5 api:23 version:6.0.1
02-20 10:48:44.115 10861-10861/? I/Runtime_iHealthDM: init()
02-20 10:48:44.117 10861-10861/? W/Runtime_iHealthDM: iHealthLibrary Version:ASDK_2.3.2
02-20 10:48:44.118 10861-10861/? W/Runtime_iHealthDM: Manufacturer:LGE  Model:Nexus 5  api:23  version:6.0.1
02-20 10:48:44.158 10861-10861/? I/Runtime_iHealthDM: registerClientCallback(com.ihealth.sdk.MainActivity$2@985c972)
02-20 10:48:44.174 10861-10904/? D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
02-20 10:48:44.187 10861-10861/? V/Runtime_iHealthDM: network name：WIFI
02-20 10:48:44.222 10861-10904/? I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 10/21/15, 369a2ea, I96aee987eb
02-20 10:48:44.224 10861-10904/? I/OpenGLRenderer: Initialized EGL, version 1.4
02-20 10:48:49.982 10861-10861/com.ihealth.sdk I/Runtime_iHealthDM: startDiscovery(2)
02-20 10:48:49.985 10861-10861/com.ihealth.sdk V/Runtime_ble: scan(true)
02-20 10:48:49.987 10861-10861/com.ihealth.sdk D/BluetoothAdapter: startLeScan(): null
02-20 10:48:49.990 10861-10861/com.ihealth.sdk D/BluetoothAdapter: STATE_ON
02-20 10:48:49.992 10861-10875/com.ihealth.sdk D/BluetoothLeScanner: onClientRegistered() - status=0 clientIf=5
02-20 10:48:50.100 10861-10861/com.ihealth.sdk I/Runtime_iHealthDM: onScanDevice(004D3206C65A, AM3S, -70, {})
02-20 10:48:50.101 10861-10861/com.ihealth.sdk I/MainActivity: onScanDevice - mac:004D3206C65A - deviceType:AM3S - rssi:-70 -manufactorData:{}
02-20 10:48:56.797 10861-10861/com.ihealth.sdk I/Runtime_iHealthDM: onScanDevice(004D3206DF17, AM3S, -66, {})
02-20 10:48:56.811 10861-10861/com.ihealth.sdk I/MainActivity: onScanDevice - mac:004D3206DF17 - deviceType:AM3S - rssi:-66 -manufactorData:{}
02-20 10:48:57.908 10861-10861/com.ihealth.sdk V/Runtime_iHealthDM: net is unavailable
02-20 10:49:01.997 10861-11189/com.ihealth.sdk V/Runtime_ble: scan(false)
02-20 10:49:01.998 10861-11189/com.ihealth.sdk D/BluetoothAdapter: stopLeScan()
02-20 10:49:02.000 10861-11189/com.ihealth.sdk D/BluetoothAdapter: STATE_ON
02-20 10:49:02.002 10861-10861/com.ihealth.sdk I/Runtime_iHealthDM: onScanFinish()
02-20 10:49:39.883 10861-10861/com.ihealth.sdk V/Runtime_iHealthDM: network name：WIFI

**Comment by qqskim** [comment]
Condition 3:
SDK demo(android level 25),  Discover together(AM3S BG5), Nexus 5x(6.0.1), Log Jar(https://github.com/iHealthDeviceLabs/iHealthDeviceLabs-Android/blob/master/lib/iHealthLibrary_2.3.2log.jar <https://github.com/iHealthDeviceLabs/iHealthDeviceLabs-Android/blob/master/lib/iHealthLibrary_2.3.2log.jar>)

**Comment by qqskim** [comment]
Condition 4:
SDK demo(android level 25),  Discover together(AM3S), Nexus 5x(6.0.1), Log Jar(V2.3.1)

**Comment by qqskim** [comment]
build.gradle

android {
    compileSdkVersion 23
    buildToolsVersion '23.0.2'

    defaultConfig {
        applicationId "com.ihealth.sdk"
        minSdkVersion 14
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    sourceSets {
        main {
            jniLibs.srcDirs = ['libs']
        }
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23+'
    compile 'com.android.support:design:23+'
}

**Comment by ivl** [comment]
Can you check please again with compileSdkVersion 25
    buildToolsVersion "25.0.1"

**Comment by ivl** [comment]
@qqskim we will prepare logs for you little bit later. Thanks

**Comment by qqskim** [comment]
build.gradle as follows, Demo works well..

apply plugin: 'com.android.application'

android {
    compileSdkVersion 25
    buildToolsVersion '25.0.1'

    defaultConfig {
        applicationId "com.ihealth.sdk"
        minSdkVersion 14
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    sourceSets {
        main {
            jniLibs.srcDirs = ['libs']
        }
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23+'
    compile 'com.android.support:design:23+'
}

**Comment by ipodib** [comment]
As @ivl mentioned we can provide logs from your example app. I've changed targetSdkVersion to 25 in gradle file. Bluetooth is turned on and appropriate devices selected in the demo app. After that I've started discovering AM3S on Nexus 5X (6.0.1) and see the following logs (log version of library were used):

```
I/Runtime_iHealthDM: startDiscovery(2)
V/Runtime_ble: scan(true)
D/BluetoothAdapter: startLeScan(): null
D/BluetoothAdapter: STATE_ON
D/BluetoothLeScanner: onClientRegistered() - status=0 clientIf=5
V/Runtime_ble: scan(false)
D/BluetoothAdapter: stopLeScan()
D/BluetoothAdapter: STATE_ON
I/Runtime_iHealthDM: onScanFinish()
```

And the same I see for HS4 device (scales is turned on):

```
I/Runtime_iHealthDM: startDiscovery(10)
V/Runtime_ble: scan(true)
D/BluetoothAdapter: startLeScan(): null
D/BluetoothAdapter: STATE_ON
D/BluetoothLeScanner: onClientRegistered() - status=0 clientIf=5
V/Runtime_ble: scan(false)
D/BluetoothAdapter: stopLeScan()
D/BluetoothAdapter: STATE_ON
I/Runtime_iHealthDM: onScanFinish()
```

In case targetSdkVersion=22 everything works as expected. Maybe you use some deprecated function inside library that leads to this problem?

Thanks.

**Comment by ipodib** [comment]
Also adding logs when targetSdkVersion=22.
For AM3S:

```
I/Runtime_iHealthDM: startDiscovery(2)
V/Runtime_ble: scan(true)
D/BluetoothAdapter: startLeScan(): null
D/BluetoothAdapter: STATE_ON
D/BluetoothLeScanner: onClientRegistered() - status=0 clientIf=5
I/Runtime_iHealthDM: onScanDevice(004D3203A94E, AM3S, -71, {})
I/MainActivity: onScanDevice - mac:004D3203A94E - deviceType:AM3S - rssi:-71 -manufactorData:{}
V/Runtime_ble: scan(false)
D/BluetoothAdapter: stopLeScan()
D/BluetoothAdapter: STATE_ON
I/Runtime_iHealthDM: onScanFinish()
```

For HS4:

```
I/Runtime_iHealthDM: startDiscovery(10)
V/Runtime_ble: scan(true)
D/BluetoothAdapter: startLeScan(): null
D/BluetoothAdapter: STATE_ON
D/BluetoothLeScanner: onClientRegistered() - status=0 clientIf=5
I/Runtime_iHealthDM: onScanDevice(9059AF25C424, HS4, -59, {})
I/MainActivity: onScanDevice - mac:9059AF25C424 - deviceType:HS4 - rssi:-59 -manufactorData:{}
V/Runtime_ble: scan(false)
D/BluetoothAdapter: stopLeScan()
D/BluetoothAdapter: STATE_ON
I/Runtime_iHealthDM: onScanFinish()
```

As you can see devices discovered successfully.

**Comment by qqskim** [comment]
Not include deprecated api, because SDK demo (with targetSdkVersion 25) works well with my Nexus 5 (6.0.1).

**Comment by jzhw0130** [comment]
@ipodib 
Could you send me the sdk demo you modified? 

Moreover, help me do a test with Nexus 5X, discover AM3S and BG5 together,  then send me the log.

Thanks very much

**Comment by jzhw0130** [comment]
@ivl @ipodib 

Could you do a test with the beta version? 
[iHealthLibrary_2.3.2.10_log.jar.zip](https://github.com/iHealthDeviceLabs/iHealthDeviceLabs-Android/files/787573/iHealthLibrary_2.3.2.10_log.jar.zip)

**Comment by jzhw0130** [comment]
@ivl @ipodib 

Make sure check the permission:

`    private void checkPermissions() {
        StringBuilder tempRequest = new StringBuilder();
        if (ActivityCompat.checkSelfPermission(this, Manifest.permission.WRITE_EXTERNAL_STORAGE) != PackageManager.PERMISSION_GRANTED) {
            tempRequest.append(Manifest.permission.WRITE_EXTERNAL_STORAGE + ",");
        }
        if (ActivityCompat.checkSelfPermission(this, Manifest.permission.RECORD_AUDIO) != PackageManager.PERMISSION_GRANTED) {
            tempRequest.append(Manifest.permission.RECORD_AUDIO + ",");
        }
        if (ActivityCompat.checkSelfPermission(this, Manifest.permission.ACCESS_FINE_LOCATION) != PackageManager.PERMISSION_GRANTED) {
            tempRequest.append(Manifest.permission.ACCESS_FINE_LOCATION + ",");
        }
        if (tempRequest.length() > 0) {
            tempRequest.deleteCharAt(tempRequest.length() - 1);
            ActivityCompat.requestPermissions(this, tempRequest.toString().split(","), REQUEST_PERMISSIONS);
        }
    }`

**Comment by jzhw0130** [comment]
@ivl @ipodib 

Make sure the permission as follows:

![1](https://cloud.githubusercontent.com/assets/12521790/23128227/158e72e6-f7b9-11e6-892f-c101e91db9af.png)
![2](https://cloud.githubusercontent.com/assets/12521790/23128243/2430cef2-f7b9-11e6-9ea7-96d211c37d8e.png)
![3](https://cloud.githubusercontent.com/assets/12521790/23128246/26ec8d52-f7b9-11e6-8d5b-ad59a2062812.png)
![4](https://cloud.githubusercontent.com/assets/12521790/23128249/29ab916e-f7b9-11e6-848b-430ccad74f1c.png)

**Comment by ivl** [comment]
@jzhw0130 We checked these permissions from beginning. It was first place (after checking manifest file).  Anyway we are using your demo app without any modification except gradдe file. Its sounds strange but only this helped to resolve issue.

**Comment by jzhw0130** [comment]
@ivl 
I coud not get your problem now..
Related different target level , only  effect the permission. 
Target level<23, no need to request runtime permission, only  need set permission on manifest file.
Target levet>=23, need to set permission on file, also need to request runtime permission.

Could send the photo as I sent above?

**Comment by jzhw0130** [comment]
@ivl 
Send me the demo you modified, thanks

**Comment by ipodib** [comment]
@jzhw0130 Here you can find logs when I set targetSdkVersion=25 and started discovering with HS4 and BG5. All permissions granted. As you can see from logs below devices discovered. But as I mentioned before, when I start discovering only HS4 - it doesn't work.

```
I/Runtime_iHealthDM: startDiscovery(100000010)
V/Runtime_iHealthDM: ACTION_FOUND(null, 28:CF:E9:03:C2:EA)
V/Runtime_iHealthDM: ACTION_FOUND(Body Scale, 90:59:AF:25:C4:24)
I/Runtime_iHealthDM: onScanDevice(9059AF25C424, HS4, 0, {})
I/MainActivity: onScanDevice - mac:9059AF25C424 - deviceType:HS4 - rssi:0 -manufactorData:{}
V/Runtime_iHealthDM: ACTION_FOUND(null, 69:95:51:02:3B:0B)
V/Runtime_iHealthDM: ACTION_FOUND(null, 67:E6:6F:3B:62:6B)
V/Runtime_iHealthDM: ACTION_FOUND(null, 54:90:A2:3C:A2:FB)
V/Runtime_iHealthDM: ACTION_FOUND(AM3S, 00:4D:32:03:A9:4E)
V/Runtime_iHealthDM: ACTION_FOUND(BG5 B960FB, 8C:DE:52:B9:60:FB)
I/Runtime_iHealthDM: onScanDevice(8CDE52B960FB, BG5, 0, {})
I/MainActivity: onScanDevice - mac:8CDE52B960FB - deviceType:BG5 - rssi:0 -manufactorData:{}
V/Runtime_iHealthDM: ACTION_FOUND(null, 28:CF:E9:03:C2:EA)
V/Runtime_iHealthDM: ACTION_FOUND(Body Scale, 90:59:AF:25:C4:24)
V/Runtime_iHealthDM: ACTION_FOUND(null, 54:90:A2:3C:A2:FB)
V/Runtime_iHealthDM: ACTION_FOUND(null, 67:E6:6F:3B:62:6B)
V/Runtime_iHealthDM: ACTION_FOUND(AM3S, 00:4D:32:03:A9:4E)
V/Runtime_iHealthDM: ACTION_FOUND(null, 4E:60:F8:73:1A:57)
V/Runtime_iHealthDM: ACTION_FOUND(BG5 B960FB, 8C:DE:52:B9:60:FB)
V/Runtime_iHealthDM: ACTION_FOUND(Body Scale, 90:59:AF:25:C4:24)
V/Runtime_iHealthDM: ACTION_FOUND(null, 67:E6:6F:3B:62:6B)
V/Runtime_iHealthDM: ACTION_FOUND(null, 28:CF:E9:03:C2:EA)
V/Runtime_iHealthDM: ACTION_FOUND(null, 54:90:A2:3C:A2:FB)
V/Runtime_iHealthDM: ACTION_FOUND(AM3S, 00:4D:32:03:A9:4E)
V/Runtime_iHealthDM: ACTION_FOUND(BG5 B960FB, 8C:DE:52:B9:60:FB)
V/Runtime_iHealthDM: ACTION_FOUND(macmini337, AC:29:3A:EE:F5:23)
I/Runtime_iHealthDM: stopBTScan()
I/Runtime_iHealthDM: onScanFinish()
```

When I tried build that you sent in previous comments the same situation occurs: when HS4 selected only - discovering doesn't work. Here logs:

```
I/Runtime_iHealthDM: startDiscovery(10)
V/Runtime_ble: scan(true)
D/BluetoothAdapter: startLeScan(): null
D/BluetoothAdapter: STATE_ON
D/BluetoothLeScanner: onClientRegistered() - status=0 clientIf=5
V/Runtime_ble: scan(false)
D/BluetoothAdapter: stopLeScan()
D/BluetoothAdapter: STATE_ON
I/Runtime_iHealthDM: onScanFinish()
```

**Comment by ipodib** [comment]
@jzhw0130 Here is the link to project that I've used:
https://www.dropbox.com/s/xmbiolwwppywie9/Android_SDK.zip?dl=0

This is example that located release build that I downloaded from github.

**Comment by ipodib** [comment]
Here is screenshot of permissions page.  As I mentioned before: we do not change anything in example project that comes with release version of iHealth SDK except gradle file. So there is no any additional code that we write by our own. It's pure example project

![screenshot_20170220-093640](https://cloud.githubusercontent.com/assets/17120906/23129401/341d7cb2-f78b-11e6-9d84-2591f419c69a.png)

**Comment by ivl** [comment]
@qqskim  @jzhw0130 Can it be related to devices firmware? We are using pretty old firmware on health devices. Can you check what firmware version on your HS4?

**Comment by ivl** [comment]
@qqskim @jzhw0130 but no. Because it worked on previous SDK version.

**Comment by qqskim** [comment]
Could you make sure SDK(2.3.1) works well on Nexus 5x (Target api level 25) ?

**Comment by ivl** [comment]
@qqskim yes it works fine. Because issues were reported by our QA team only after upgrade to 2.3.2.
We are always used API level > 23 and always requested permissions before

**Comment by jzhw0130** [comment]
@ivl  @ipodib 

Help  do a test with the new version, thanks.
Then send the log



[iHealthLibrary_2.3.2.10_log.jar.zip](https://github.com/iHealthDeviceLabs/iHealthDeviceLabs-Android/files/787845/iHealthLibrary_2.3.2.10_log.jar.zip)

**Comment by jzhw0130** [comment]
@ivl 

Moreover, help do a test with SDK (2.3.1), then send the log.
I am very confused now, we did not make change for the discovery process from V2.3.1 to V2.3.2.

**Comment by ivl** [comment]
@jzhw0130 what about 2.3.0?
We will upload logs from 2.3.1 later

**Comment by ivl** [comment]
@jzhw0130 if you don't touch observing? Then why did you changed target sdk in 2.3.2 to 22?
In previous was 23  in gradle file.

**Comment by ipodib** [comment]
@jzhw0130 I've checked V2.3.1 and I see the same issue here: HS4 is not discovered.

```
I/Runtime_iHealthDM: startDiscovery(10)
V/Runtime_ble: scan(true)
D/BluetoothAdapter: startLeScan(): null
D/BluetoothAdapter: STATE_ON
D/BluetoothLeScanner: onClientRegistered() - status=0 clientIf=5
V/Runtime_ble: scan(false)
D/BluetoothAdapter: stopLeScan()
D/BluetoothAdapter: STATE_ON
I/Runtime_iHealthDM: onScanFinish()
```

**Comment by ipodib** [comment]
@jzhw0130 Beta build that you sent me doesn't work as well.

**Comment by ivl** [comment]
@ipodib its why our QA reported that worked - because they started observing AM3S or HS4 only after BG5  paired. And in pair with BG5 it works. But without not.

**Comment by qqskim** [comment]
When target < 23, no need open the location function, no need request runtime permission for location.
When target >=23,  need  open the location function, and request runtime permission for location, and add permission request on manifest file.

So we change target to 22.

**Comment by jzhw0130** [comment]
@ivl @ipodib 

Please check the location function is open or closed??

![74ad2a935655b0adb3c2d92c0ff79672](https://cloud.githubusercontent.com/assets/12521790/23147176/d07c4f3e-f817-11e6-9075-d59b132e396e.jpg)

**Comment by qqskim** [comment]
Thank you for your information.

Check one detail:

Pair BG5 with Nexus 5X on bluetooth page, then only discover HS4 or AM3S (not discover BG5 and HS4 together), work well ?

**Comment by ipodib** [comment]
@jzhw0130 Location was turned off. I don't see the any reason why sdk needs a location.

@qqskim I've tried to pair BG5 on bluetooth page and then started discovering only HS4. Discovering doesn't work. Here logs from device:

```
I/Runtime_iHealthDM: startDiscovery(10)
V/Runtime_ble: scan(true)
D/BluetoothAdapter: startLeScan(): null
D/BluetoothAdapter: STATE_ON
D/BluetoothLeScanner: onClientRegistered() - status=0 clientIf=5
V/Runtime_ble: scan(false)
D/BluetoothAdapter: stopLeScan()
D/BluetoothAdapter: STATE_ON
I/Runtime_iHealthDM: onScanFinish()
```

**Comment by qqskim** [comment]
Please turn on the location, then do a test.

**Comment by qqskim** [comment]
Because ivl said ‘...Interesting detail. It could be observed if gluco BG5 also is discovering...’.

So I want to known more details about the situation.

**Comment by jzhw0130** [comment]
@ivl @ipodib 

Bluetooth and Location:

http://stackoverflow.com/questions/33013818/bluetoothlescanner-startscan-with-android-6-0-does-not-discover-devices

**Comment by ivl** [comment]
@jzhw0130 we will do test. But then - can you turn off Location in your Nexus  and check our case?

**Comment by jzhw0130** [comment]
@ivl 

Turn off location,  could not discover HS4 and AM3S.

**Comment by ivl** [comment]
@jzhw0130 cool that we found root. But then for me its  not clear why if to start observing BG5 together with HS4 it works?

**Comment by jzhw0130** [comment]
@ivl 

There is 2 api for discover bluetooth device.

Api 1 -- discover only bluetooth low energy (Ble) device .
Api 2-- discover bluetooth low energy and bluetooth 3.0 device together.

BG5: bluetooth 3.0
AM3S HS4: bluetooth low energy 

If discover HS4 only, SDK will call Api 1. (Efficient)
If discover HS4 and BG5 together, SDK will call Api2.  (Less Efficient for HS4)

**Comment by ivl** [comment]
@jzhw0130 Got you. But then why if location is disabled you are not checking it and use less efficient method? Anyway less efficient method better than unable to discover device?

**Comment by jzhw0130** [comment]
@ivl  

Api 1 could not discover BG5.  
But you need discover BG5 and AM3S together, so SDK have to call Api 2 .
Api 2 is less efficient, but no need location.

**Comment by ivl** [comment]
@jzhw0130 Our application is using  iHealth devices. AM3S, HS4, BG5. We need that user be able to discover all of them. And we can't predict what user will select to discover. Its good when BG5 was paired - in this case he will be able to discover HS4 and AM3S. But what if glucometer was disabled in user care plan? You are providing general interface - startDiscovery. So you need to decide what needed to be able to discover what SDK user want to get.

**Comment by jzhw0130** [comment]
@ivl 

So your application have 2 choices:
1. Set target level < 23
2. Make sure location is available, as bluetooth is enabled.

**Comment by ivl** [comment]
@jzhw0130 Both options are not acceptable for us. I don't see any reasons why you cant add checking if locations is enabled and select correct way to observe devices.

**Comment by jzhw0130** [comment]
@ivl 
Maybe later

**Comment by jzhw0130** [comment]
@ivl 

Try the beta version: 

https://github.com/iHealthDeviceLabs/iHealthDeviceLabs-Android/blob/master/lib/beta/iHealthLibrary_2.3.2.13.jar

Attentation: This way (Api2 discover bluetooth low energy device) is unreliable.
