### ISSUE TITLE
Can't connect to HS4 with firmware 1.0.1

### ISSUE THREAD

**Issue by ivl** [iHealthDeviceLabs/iHealthDeviceLabs-Android#48]
Can't connect HS4 with firmware 1.0.1 after discovering. Always connection error.
HS4 with firmware 1.0.4 connected without any issues.
Phone Samsung Galaxy J3. Android 6.0.1.

**Comment by qqskim** [comment]
Please use log jar, make a test, then send logs

**Comment by hashtaag-vinay-sasalatti** [comment]
Hi @qqskim 

i am having the same issue too , i am using the firmware 1.0.1 , works well in IOS but in android its having this issue , below are the logs for android-sdk sample 


02-27 12:23:24.671 6887-6887/com.ihealth.sdk D/BluetoothAdapter: startLeScan(): null

02-27 12:23:24.681 6887-6904/com.ihealth.sdk D/BluetoothLeScanner: onClientRegistered() - status=0 clientIf=5

02-27 12:23:24.741 6887-6887/com.ihealth.sdk I/MainActivity: onScanDevice - mac:8CDE52ABF63B - deviceType:HS4 - rssi:-69 -manufactorData:{}

02-27 12:23:33.291 6887-6887/com.ihealth.sdk I/MainActivity: mac = 8CDE52ABF63B

02-27 12:23:33.291 6887-6887/com.ihealth.sdk D/BluetoothAdapter: stopLeScan()

02-27 12:23:33.301 6887-6887/com.ihealth.sdk D/BluetoothGatt: connect() - device: 8C:DE:52:AB:F6:3B, auto: false

02-27 12:23:33.301 6887-6887/com.ihealth.sdk D/BluetoothGatt: registerApp()

02-27 12:23:33.301 6887-6887/com.ihealth.sdk D/BluetoothGatt: registerApp() - UUID=1facc8dc-53a3-43c5-967a-86d625f02c1a

02-27 12:23:33.301 6887-6903/com.ihealth.sdk D/BluetoothGatt: onClientRegistered() - status=0 clientIf=5

02-27 12:23:33.401 6887-6887/com.ihealth.sdk E/MainActivity: mac:8CDE52ABF63B deviceType:HS4 status:0 errorid:0 -manufactorData:null

02-27 12:23:35.931 6887-6903/com.ihealth.sdk D/BluetoothGatt: onClientConnectionState() - status=133 clientIf=5 device=8C:DE:52:AB:F6:3B

02-27 12:23:35.931 6887-6904/com.ihealth.sdk D/BluetoothGatt: onClientConnectionState() - status=133 clientIf=5 device=8C:DE:52:AB:F6:3B

02-27 12:23:36.031 6887-6887/com.ihealth.sdk E/MainActivity: mac:8CDE52ABF63B deviceType:HS4 status:4 errorid:133 -manufactorData:null

02-27 12:23:36.431 6887-6904/com.ihealth.sdk D/BluetoothGatt: cancelOpen() - device: 8C:DE:52:AB:F6:3B

02-27 12:23:36.431 6887-6904/com.ihealth.sdk D/BluetoothGatt: close()

02-27 12:23:36.431 6887-6904/com.ihealth.sdk D/BluetoothGatt: unregisterApp() - mClientIf=5

02-27 12:23:36.531 6887-6887/com.ihealth.sdk E/MainActivity: mac:8CDE52ABF63B deviceType:HS4 status:3 errorid:133 -manufactorData:null

please help me out ,

Thanks,  
vinay

**Comment by ivl** [comment]
@hashtaag-vinay-sasalatti exactly. iOS works well while Android don't. Thanks for update.

**Comment by hashtaag-vinay-sasalatti** [comment]
HI @qqskim 

any update on this issue , i am getting **status:3 errorid:133**  and i am in between the integration process , can you help me out on this .

thanks ,
Vinay

**Comment by qqskim** [comment]
Hi

Sorry for later reply.

Could you help do a test?
1. Download ‘iHealth Myvitals’ from Apple Store. 
2. Connect HS4 with iOS device
3. Then app will upgrade the firmware of HS4.
4. After upgrade, then try connect with your android phone.

Thanks


Jing

**Comment by hashtaag-vinay-sasalatti** [comment]
@qqskim , sure i will try and update you on that 

Thanks ,
Vinay

**Comment by qqskim** [comment]
Thanks

Moreover,  All your android phones can not connect HS4?  or some can connect, some can not?

**Comment by ivl** [comment]
@qqskim after upgrade - it easily was connected. But issue still present for our customer. Our customer has tons of scales with old firmware. Main our goal to avoid situation when user needs to download any 3d party software. So it affects our customer - for internal testing its ok. But not for mass usage.

**Comment by hashtaag-vinay-sasalatti** [comment]
Hi @qqskim 

i did the following - 
1. Download ‘iHealth Myvitals’ from Apple Store.
2. Connect HS4 with iOS device
3. Measured the Weight
4. Navigated to Set Up My Devices and checked firmware version , it is still 1.0.1 (**Dont see any update**) 

can you guid me on this , because its a blocker for me now 

PS- @ivl please give me some suggestions , if you have updated the firmware 

Thanks ,
Vinay

**Comment by ivl** [comment]
@hashtaag-vinay-sasalatti if you go to about screen on paired device - you will see check update button. Click it and it will install new firmware

**Comment by jzhw0130** [comment]
@ivl 

Did you use  'iHealth MyVitals'(Android) to upgrade HS4?  Or 'iHealth MyVitals'(iOS)?

**Comment by jzhw0130** [comment]
@ivl 

All your Android phones can not connect HS4(1.0.1)? Or part of phones can, part can not?

**Comment by hashtaag-vinay-sasalatti** [comment]
@ivl 

![img_0969](https://cloud.githubusercontent.com/assets/19309575/23446302/1dd5f4a0-fe68-11e6-9e9a-a20555f945b6.PNG)
![img_0970](https://cloud.githubusercontent.com/assets/19309575/23446303/1e8032ee-fe68-11e6-847d-8c8a5ea1ed11.PNG)

Navigated to Set Up My Devices screen , and about screen on paired device , i dont c an check update button 

can u help me on this please ,

Thanks ,
Vinay

**Comment by ivl** [comment]
jzhw0130We  @hashtaag-vinay-sasalatti  - we have used iOS version of application to upgrade scale.

**Comment by hashtaag-vinay-sasalatti** [comment]
Hi @ivl , i am using IOS too , but unable to see check update button

**Comment by qqskim** [comment]
Hi

Which country are you from?   How many HS4(1.0.1) do you have?  Which store do you by these HS4?
We will try to solve your problem.

Thanks


Jing

**Comment by qqskim** [comment]
Hi

Which country are you from?   How many HS4(1.0.1) do you have?  Which store do you by these HS4?
We will try to solve your problem.

Thanks


Jing

**Comment by jdjfoley** [comment]
Just a bit of input on my end. I was having connection errors with HS4
(status 3) while trying to connect. I created another activity with only
hs4 logic, i was able to connect to the device when everything happened
within a second or two. if there was any delay i would get status 3. After
connecting, i upgraded and was able to connect more consistently.

~ James

**Comment by jzhw0130** [comment]
@jdjfoley 

Thanks for your feedback.
What's the 'delay'?  Between discovery and connect?

**Comment by jdjfoley** [comment]
For example when I step on the scale to make it discoverable it shows up on
the list view. By pressing the hs4 I move to another activity which
initiates SDK author ... Connect....Control. if I do this quickly as in. As
soon as it appears on the list view I can get connection . If I wait too
long to start connection after discovering then I'll get the error.
Hope that made sense.

J

**Comment by jzhw0130** [comment]
@jdjfoley 

Sure

HS4 broadcast with high frequency when you step on the scale.
After long time, HS4 will broadcast with low frequency for saving battery.

With high frequency, it it easy to connect, otherwise it is hard to connect for part of phones.

**Comment by hashtaag-vinay-sasalatti** [comment]
Hi @qqskim ,

Currently i am in india and i have one HS4, with firmware 1.0.1 which works well with IOS but in android when i try to connect i am getting **DEVICE_STATE_CONNECTIONFAIL = 3** and **finally mac:8CDE52ABF63B deviceType:HS4 status:4 errorid:133 -manufactorData:null** , i have checked this in 3-4 devices and getting the same issue , 

as you guys suggested to update the firmware by connecting the HS4 with IOS IhealthMyVitals app ,
i tried doing it and dint see any update firmware button in the app , i have attache the screenshots in the previous post above ,

in all the android devices i tested IhealthMyvitals app works perfectly with HS4 , but the  the iHealthDeviceLabs-Android sample SDK app is getting the above mentioned issue , now i am stuck with this HS4 integration in my application , can you guys help me out on this ?


thanks ,
vinay

**Comment by jzhw0130** [comment]
@hashtaag-vinay-sasalatti 

Are you sure 'iHealth MyVitals' works well with HS4 on all your Android phones???
If yes.
In my opinion, if 'iHealth MyVitals' works, SDK demo  should work well.

Could you make a video when you test the SDK demo with HS4?
Moreover, copy all the logs from Logcat, send to me

Thanks

**Comment by jzhw0130** [comment]
@hashtaag-vinay-sasalatti 
Moreover, your product is HS4? or HS4S?

**Comment by hashtaag-vinay-sasalatti** [comment]
Hi @jzhw0130 , @qqskim 

the product is HS4S !! , not HS4 @jzhw0130 , thanks for asking me this question which led me to check on the proper model and get this issue fixed , my bad 

now all is in place for my integration the SDK Demo is fine sorry for all the misunderstandings  ;P

Thanks @jzhw0130 , @qqskim 

Cheers ,
Vinay

**Comment by qqskim** [comment]
Good news!

**Comment by ivl** [comment]
@qqskim you can close the issue. Cause we have checked that it relates to HS4S firmware. Not HS4. Sorry for misunderstanding

**Comment by jzhw0130** [comment]
@ivl  ok

**Comment by hashtaag-vinay-sasalatti** [comment]
@ivl @qqskim @jzhw0130  

I would like to notify you all that in IOS sdk the HS4 controllers manage both HS4 and HS4S devices  , but in android sdk we have separate controllers for both HS4 and HS4S devices , this is the reason for all the confusion  in my case , but anyhow all is fine and sorted now ;P

Cheers ,
Vinay

**Comment by jzhw0130** [comment]
@hashtaag-vinay-sasalatti 
You are right.
HS4 work with bluetooth low energy for iOS and Android.
HS4S work with  bluetooth low energy for iOS, but  bluetooth 3.0 for Android (to fit more android phones).
So we have to make different type and controller for Android.
