### ISSUE TITLE
Issues with iHealth servers

### ISSUE THREAD

**Issue by ivl** [iHealthDeviceLabs/iHealthDeviceLabs-Android#49]
Issues with iHealth servers

{
	"QueueNum": 111111,
	"Result": "3",
	"ResultMessage": "500",
	"ReturnValue": "System.Data.SqlClient.SqlException (0x80131904): Connection Timeout Expired.  The timeout period elapsed during the post-login phase.  The connection could have timed out while waiting for server to complete the login process and respond; Or it could have timed out while attempting to create multiple active connections.  The duration spent while attempting to connect to this server was - [Pre-Login] initialization=0; handshake=12166; [Login] initialization=0; authentication=0; [Post-Login] complete=1998;  ---> System.ComponentModel.Win32Exception (0x80004005): The wait operation timed out\u000d\u000a   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\u000d\u000a   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\u000d\u000a   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\u000d\u000a   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\u000d\u000a   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\u000d\u000a   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\u000d\u000a   at System.Data.SqlClient.SqlConnection.Open()\u000d\u000a   at Microsoft.Practices.EnterpriseLibrary.Data.Database.GetNewOpenConnection()\u000d\u000a   at Microsoft.Practices.EnterpriseLibrary.Data.Database.ExecuteReader(DbCommand command)\u000d\u000a   at Andon.iHealthLabs.Dal.Utility.ExecuteReader(Database database, DbCommand dbCommand)\u000d\u000a   at Andon.iHealthLabs.Dal.SqlClient.SqlApplicationUserProviderBase.Find(TransactionManager transactionManager, IFilterParameterCollection parameters, String orderBy, Int32 start, Int32 pageLength, Int32& count)\u000d\u000a   at Andon.iHealthLabs.Dal.Bases.EntityProviderBaseCore`2.Find(TransactionManager transactionManager, IFilterParameterCollection parameters, String orderBy)\u000d\u000a   at Andon.iHealthLabs.BLL.API5.GetScSvFromDB.VertifyApiCertificate(String aSC, String aSV, HttpContext context)\u000d\u000a   at Andon.iHealthLabs.BLL.API5.Handler.UserExistForThirdHandler.ProcessRequest(HttpContext context)\u000d\u000aClientConnectionId:c90a77e5-92da-4ecf-8e71-5a106090050a",
	"TS": 1490013778
}

**Comment by qqskim** [comment]
Always? Sometimes?

**Comment by ivl** [comment]
@qqskim always

**Comment by jzhw0130** [comment]
@ivl 
Server is ok now.
