### ISSUE TITLE
Issue in Pairing Pulse Oximeter

### ISSUE THREAD

**Issue by manikavi** [iHealthDeviceLabs/iHealthDeviceLabs-Android#5]
Hi,

      I'm  facing Problem in detecting and pairing Pulse Oximeter Device,Please help me to resolve this issue

Model Number :- PO3

Issues :- 

1.device is showing in Bluetooth page after every restart
2.getting incorrect Pin number while Pairing the device,we tried with 0000,1234,123456,111111,2222

**Comment by manikavi** [comment]
fixed my issue..Auto Pairing is happening,for this we have to keep finger inside **SPO2** device..

**Comment by jzhw0130** [comment]
@manikavi 
Sorry for  later reply.
PO3 use bluetooth low energy, not bluetooth 3.0.
No need to pair on bluetooth page.   App will pair automatically.

**Comment by manikavi** [comment]
**@jzhw0130**

no Problem,I came to know about this while testing my code...Thanks for Letting me know ..
