### ISSUE TITLE
Q1. how can i know when the iHeaithDevice is OFF (any callback ?),   Q2. unable to discover 2 devices in same time , getting only one discovered and connected at a given time 

### ISSUE THREAD

**Issue by hashtaag-vinay-sasalatti** [iHealthDeviceLabs/iHealthDeviceLabs-Android#51]
Q1. how can i know when the iHeaithDevice is OFF (any callback ?), Q2. unable to discover 2 devices in same time , getting only one discovered and connected at a given time

**Comment by hashtaag-vinay-sasalatti** [comment]
@jzhw0130 , @qqskim , guys can u help me out on this ?

**Comment by jzhw0130** [comment]
@hashtaag-vinay-sasalatti 
Q1.
com.ihealth.communication.manager.iHealthDevicesCallback
public void onDeviceConnectionStateChange(String mac,
                                          String deviceType,
                                          int status,
                                          int errorID)
Callback indicating when a iHealth device has connected/disconnect/connecting/reconnecting.
Parameters:
mac - iHealth device mac
deviceType - iHealth device type
status - status of the connecting, connected, disconnect or reconnecting operation iHealthDevicesManager.DEVICE_STATE_CONNECTING iHealthDevicesManager.DEVICE_STATE_CONNECTIONFAIL iHealthDevicesManager.DEVICE_STATE_CONNECTED iHealthDevicesManager.DEVICE_STATE_DISCONNECTED iHealthDevicesManager.DEVICE_STATE_RECONNECTING
errorID - The error of connect fail. For BT3.0, errorID: 1, you have to pair iHealth device with your phone on bluetooth page manually. For BLE, errorID: returned by android os api android.bluetooth.BluetoothGattCallback.onConnectionStateChange(BluetoothGatt, int, int).

Q2.
Why?
Do as : 
            iHealthDevicesManager.getInstance().startDiscovery(iHealthDevicesManager.DISCOVERY_AM4|iHealthDevicesManager.DISCOVERY_HS4);

**Comment by hashtaag-vinay-sasalatti** [comment]
@jzhw0130 


Q1 - 
hey its not hitting the callback when device is off (its paired with phone already) bp7 and hs4s
onDeviceConnectionStateChange(String mac,String deviceType,int status,int errorID)
is not been called ;(

logs ---

03-24 11:50:10.525 3062-3220/? E/bt-btm: Device already in IRK list
03-24 11:50:10.535 3062-3220/? E/bt-btif: bte_scan_filt_param_cfg_evt, 23
03-24 11:50:11.915 3062-3220/? E/bt-btm: new address: 75:17:02:a1:72:1f
03-24 11:50:11.915 3062-3220/? E/bt-btm: new address: 75:17:02:a1:72:1f
                                         
                                         [ 03-24 11:50:11.915  3062: 3154 D/         ]
                                         cod is 0, set as unclassified
03-24 11:50:13.215 21792-22247/com.biofourmis.kardia E/onUserStatus: venkat@hashtaag.com**2
03-24 11:50:14.535 3062-3220/? E/bt-btm: Device already in IRK list
03-24 11:50:14.535 3062-3220/? E/bt-btif: bte_scan_filt_param_cfg_evt, 23
03-24 11:50:17.365 3062-3220/? E/bt-btm: new address: c8:69:cd:e9:49:ce
03-24 11:50:17.365 3062-3220/? E/bt-btm: new address: c8:69:cd:e9:49:ce
                                         
                                         [ 03-24 11:50:17.365  3062: 3154 D/         ]
                                         cod is 0, set as unclassified
03-24 11:50:18.545 3062-3220/? E/bt-btm: Device already in IRK list
03-24 11:50:18.545 3062-3220/? E/bt-btif: bte_scan_filt_param_cfg_evt, 23
03-24 11:50:20.035 3062-3220/? E/bt-btm: new address: c8:69:cd:e9:49:ce


Q2-

did this - iHealthDevicesManager.getInstance().addCallbackFilterForDeviceType(callbackId, iHealthDevicesManager.TYPE_BP7, iHealthDevicesManager.TYPE_HS4S);

its connecting to only 1st device ;(

logs -

03-24 11:57:27.705 3062-3220/? E/bt-btm: Device already in IRK list
03-24 11:57:27.705 21792-28919/com.biofourmis.kardia E/onUserStatus: venkat@hashtaag.com**2
03-24 11:57:27.715 3062-3220/? E/bt-btif: bte_scan_filt_param_cfg_evt, 23
03-24 11:57:27.725 3062-3220/? E/bt-btm: new address: 8c:de:52:ab:f6:3b
03-24 11:57:27.725 3062-3220/? E/bt-btm: new address: 8c:de:52:ab:f6:3b
                                         
                                         [ 03-24 11:57:27.725  3062: 3154 D/         ]
                                         cod is 0, set as unclassified
03-24 11:57:30.725 3062-3220/? E/bt-btm: tBTM_SEC_DEV:0xa4b1a8c8 rs_disc_pending=0
03-24 11:57:31.675 21792-21792/com.biofourmis.kardia E/Devices: mac:8CDE52B5E2F1 deviceType:BP7 status:1 errorid:0 -manufactorData:null
03-24 11:57:31.675 21792-21792/com.biofourmis.kardia E/Devices: mac:8CDE52B5E2F1 deviceType:BP7 status:1 errorid:0 -manufactorData:null
03-24 11:57:31.675 21792-21792/com.biofourmis.kardia E/Devices: mac:8CDE52B5E2F1 deviceType:BP7 status:1 errorid:0 -manufactorData:null
03-24 11:57:31.675 21792-21792/com.biofourmis.kardia E/Devices: mac:8CDE52B5E2F1 deviceType:BP7 status:1 errorid:0 -manufactorData:null
03-24 11:57:31.675 21792-21792/com.biofourmis.kardia E/Devices: mac:8CDE52B5E2F1 deviceType:BP7 status:1 errorid:0 -manufactorData:null
03-24 11:57:31.755 21792-21792/com.biofourmis.kardia E/Runtime_iHealthDM: 认证通过了，可以上传数据
03-24 11:57:35.775 21792-21792/com.biofourmis.kardia E/Runtime_iHealthDM: 认证通过了，可以上传数据
03-24 11:57:35.775 21792-21792/com.biofourmis.kardia E/Runtime_iHealthDM: 认证通过了，可以上传数据
03-24 11:57:35.775 21792-21792/com.biofourmis.kardia E/Runtime_iHealthDM: 认证通过了，可以上传数据
03-24 11:57:40.275 21792-21792/com.biofourmis.kardia E/Runtime_iHealthDM: 认证通过了，可以上传数据

thanks ,
Vinay

**Comment by jzhw0130** [comment]
@hashtaag-vinay-sasalatti 
Q1.
Try with the log version, upload the log . (https://github.com/iHealthDeviceLabs/iHealthDeviceLabs-Android/blob/master/lib/iHealthLibrary_2.3.2log.jar)

Q2.
Connect one by one, do not connect at the same time.
Connect one, wait callback. Then connect another one.

**Comment by hashtaag-vinay-sasalatti** [comment]
@jzhw0130 sure i will do that and update you ,

thanks ,
Vinay

**Comment by jzhw0130** [comment]
@hashtaag-vinay-sasalatti 

Any news?

**Comment by hashtaag-vinay-sasalatti** [comment]
@jzhw0130 

Q2. i have done Connecting one by one and it works fine 

for Q1, i am unable to know when device does not exists or if devices is off  , i just need to notify the user that there discovery failed because devices was far from reach or off , please let me know if there is any error code or any callback for this scenario , this link (https://github.com/iHealthDeviceLabs/iHealthDeviceLabs-Android/blob/master/lib/iHealthLibrary_2.3.2log.jar) is giving me 404 :)

PS - its not a blocker for me though , currently i am using a 10 secs timer and telling user if not connected, but if i get any update on this scenario it would be helpful .

thanks ,
Vinay

**Comment by qqskim** [comment]
Hi


For discover process, it will work for 12 seconds. Then the callback  will be triggered.

@Override
public void onScanFinish() {
    
}

Jing

**Comment by jzhw0130** [comment]
@hashtaag-vinay-sasalatti 

For discover process, it will work for 12 seconds. Then the callback  will be triggered.

@Override
public void onScanFinish() {

}
