### ISSUE TITLE
getDevicePermisson() crashes on Huawei Honor 7 during connecting with BP5

### ISSUE THREAD

**Issue by soshial** [iHealthDeviceLabs/iHealthDeviceLabs-Android#52]
Your vanilla SDK example app worked on my device (Huawei Honor 7), BUT in order to test how my application would work with iHealth BP5 device, I copied `MainActitivity.java` and `BP5.java` from SDK example app to my app and launched it.

![screenshot_2017-03-29-13-08-25](https://cloud.githubusercontent.com/assets/100644/24450424/81470444-1483-11e7-90ed-778a81a609dd.png)

Scan went okay, Pairing went okay. Clicking on the device (see screenshot) crashes in `getDevicePermission()`:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: __._____._____, PID: 18740
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.ihealth.communication.cloudmanager.iHealthDeviceCloudManager.getDevicePermisson(java.lang.String, java.lang.String)' on a null object reference
        at com.ihealth.communication.manager.iHealthDevicesManager.connectDevice(Unknown Source)
        at __._____._____.view.MainActivity$3.onItemClick(MainActivity.java:228)
        at android.widget.AdapterView.performItemClick(AdapterView.java:303)
        at android.widget.AbsListView.performItemClick(AbsListView.java:1151)
        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3065)
        at android.widget.AbsListView$3.run(AbsListView.java:3878)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5539)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

I kept these variables empty as it was in your example:
```
String userName = "";
String clientId = "";
String clientSecret = "";
```

I also tried to copy the keys that we had from another app of ours (doesn't work now). Nothing changed. `userStatus` is 2 in my app.

**Comment by jzhw0130** [comment]
@soshial 

You have to set userName clientId  clientSecret valid, empty is invalid.
If get useStatus = 5, connect will fail.

Send me your invalid clientId, we will check the status of your application.

**Comment by soshial** [comment]
Okay. Where to send them?

> Contact for more information:
> enterprise@ihealthlabs.com
> developer@ihealthlabs.com(US)
> louie@ihealthlabs.com(Europe)

**Comment by qqskim** [comment]
US:developer@ihealthlabs.com <mailto:developer@ihealthlabs.com>
Europe: louie@ihealthlabs.com <mailto:louie@ihealthlabs.com>
Other: jingzhiwei@ihealthlabs.com.cn <mailto:jingzhiwei@ihealthlabs.com.cn>

**Comment by soshial** [comment]
@jzhw0130, I put my iHealth dev email as `userName` and my status is 2, but the crash still occurs.

**Comment by qqskim** [comment]
What’s your clientID clientSecret and userName?

**Comment by JintoSK** [comment]
May I attach to this conversation. I have similar problem like @soshial .  I copied `MainActitivity.java` and `BP5.java` from SDK example app to my app and launched about a few days ago. It crashed like on the screenshot above. Today a registered my app on [developer.ihealthlabs.com](http://developer.ihealthlabs.com) and I added my email as userName and of course clientId and secretSecret too, but I got the same error. (I work with the same device like @soshial - BP5)

**Comment by jzhw0130** [comment]
@JintoSK 

Sure

Did you register your application on developer.ihealthlabs.com for Android platform? or iOS ? or OpenApi?

If get useStatus = 5,  your application is invalid for Android platform?
Does anyone from iHealth invite you to register ? or register by  yourself?


Jing

**Comment by JintoSK** [comment]
@jzhw0130 

I registered by myself for OpenApi, beacuse I didn't have any other choice. I did not see Android api choice to check... . How can I change this option?

**Comment by qqskim** [comment]
Hi

Please send the clientID,  I will contact our business manager who will send you a invitation.


Jing

**Comment by JintoSK** [comment]
Hi @qqskim 

Can I send the clientID to this email? **louie@ihealthlabs.com** ? 
And one more question, if I have this one application for which I testing connection and another app in which I want to use this connection. Can I send you to this email Client ID from both applications?

Thank you for your help

**Comment by qqskim** [comment]
Sure

It’s ok

**Comment by soshial** [comment]
My issue has not been resolved still. What should I do?

**Comment by qqskim** [comment]
Hi

Did you send your clientID to the email?  louie@ihealthlabs.com <mailto:louie@ihealthlabs.com> ?

**Comment by soshial** [comment]
Yes of course, but they just stopped answering me.

**Comment by JintoSK** [comment]
Both my application on [developer.ihealthlabs.eu](developer.ihealthlabs.eu) were activated, bud I have still the same problem. 
I cant connect to my device, and my userStatus is 5 with wifi on, and 4 without the internet connection... 
I am using my email from webside as **userName** and **clientID** and client secret from my profile... 
On webside, after activation I have another two numbers available, **SC & SV** numbers, but I don't know how or where can I use these... 
My application on the webside was registered and activated for OpenApi, beacuse I didn't see any other choice during registration (like on the screenshot from AndroidSDK documentation)... How can I register my app for Android platform? Or this way is correct?

**Comment by qqskim** [comment]
You have to contact our business manager Louie( louie@ihealthlabs.com <mailto:louie@ihealthlabs.com>). He will send you an invitation by a link. You can open the link to register your app for Android platform.

Jing

**Comment by jzhw0130** [comment]
@soshial @JintoSK 
Hi

Please contact our business manager Louie (louie@ihealthlabs.com), CC me(jingzhiwei@ihealthlabs.com.cn)

**Comment by soshial** [comment]
I have resolved my problem

1. I forgot to add to gradle file
```
sourceSets {
        main {
            jniLibs.srcDirs = ['libs']
        }
    }
```
2. One of `libiHealth.so` files was zero-byte. Pre API 25 devices can't log this exception properly. I redownloaded and recopied it from this repo.

**Comment by jzhw0130** [comment]
@soshial 

Good news.

**Comment by jzhw0130** [comment]
@JintoSK 

Any update?

**Comment by JintoSK** [comment]
@jzhw0130 

I still have the same problem, I sent an email to  Louie (louie@ihealthlabs.com) and I've got and answer, that he sent me an invitation. I receive one system mail, but there was only this link [http://developer.ihealthlabs.com/index.aspx](http://developer.ihealthlabs.com/index.aspx), not registration link, and i still can't register my application for Android SDK. I will send copy of this communication, if I may.

**Comment by qqskim** [comment]
Louie

Please help solve the problem, thanks

**Comment by JintoSK** [comment]
Please, I still don't have any answer... What can i do? 
Can you send me an invitation to another email, if the first does not work?

**Comment by qqskim** [comment]
Sorry

Our colleague Louie is in charge of your problem, he has resigned. 
Could you send me your clientID and account (email) again？

We will send you a invitation. 

My email: jingzhiwei@ihealthlabs.com.cn <mailto:jingzhiwei@ihealthlabs.com.cn>



Jing

**Comment by JintoSK** [comment]
Of course, I am sending an email to you right now... 
I will be waiting to the invitation. 
Thank you

**Comment by jzhw0130** [comment]
@JintoSK 

Sorry  I have not received your email.

**Comment by JintoSK** [comment]
@jzhw0130 

I don't know, where is the problem. I send it again to this email: 	**jingzhiwei@ihealthlabs.com.cn**
The subject of the email is: **Android platform Invitation**
Please let me know if you receive it.

JintoSK - (mail is from **kiikinoo@gmail.com**)

**Comment by JintoSK** [comment]
I received the invitation yesterday. After that I updated my registered application to Android SKD and downloaded SDK... Now I am still waiting, because state of my application is Not Audit... 
Does anyone have to confirm this change for me? (aplication still does not work, userStatus = 5)

Thank you very much for invitation

**Comment by JintoSK** [comment]
Hello, 
Please have another problem with connection to the BP5. 

The connection worked correctly about 16 day, until yesterday. Since yesterday I have a connection problem again. This time was my userStatus = 8. Then a start wifi on my device, and userStatus changed to userStatus = 5. Why is my verification failed? On your webside I have my registered application still in active state. 

Can you please help me with this problem? 

JintoSK

**Comment by zhaoyongguang** [comment]
@JintoSK 

Please send the userName clientID and clientSecret  to my email: <zhaoyongguang@ihealthlabs.com.cn>.
I will check the verification userStatus.

**Comment by JintoSK** [comment]
@zhaoyongguang I send you my information right now. 

Thank you for your time.

**Comment by zhaoyongguang** [comment]
@JintoSK 

I just received the confirmation from my engineer team, the problem is fixed.
Could you please check in your side?

**Comment by JintoSK** [comment]
You're right, my connection work again. 
Thank you very much for solving my problem.

**Comment by Joaos92** [comment]
@soshial Hey, I am currently having the same exact problem you had.
When I connect my android phone to a device it crashes and I get this error:

java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/io.ionic.starter-2/base.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]] couldn't find "libiHealth.so"

Could you tell me where you got the libiHealth.so because I seem to be missing this one.

Thanks
