### ISSUE TITLE
Can't find in api - glucose battery -1

### ISSUE THREAD

**Issue by jdjfoley** [iHealthDeviceLabs/iHealthDeviceLabs-Android#54]
don't see any reference to this anywhere. But bg5 connects fine but getBattery returns a battery value of -1.
What does it mean? how do I resolve?

Side note its only on 1 of my devices, my other bg5 returns the actually battery level.

Thanks in advance.
~ James

**Comment by jzhw0130** [comment]
public static final java.lang.String BATTERY_BG
The power of Battery for Bg device.
Validate Range : 0~100     -1 : not support      255: in charging

new version BG5 (Firmware Version>=6.0.0) support , otherwise not support

**Comment by jdjfoley** [comment]
Note. I resolved the issue of getting -1 when I plugged device in to charge. i checked battery while charging, got 255. check again after removing and got 98. Working now. Thank you for response.

**Comment by jzhw0130** [comment]
ok
