### ISSUE TITLE
Can't communicate with ABI device

### ISSUE THREAD

**Issue by padamuscinova** [iHealthDeviceLabs/iHealthDeviceLabs-Android#55]
Hello, I'm trying to work with the CardioLab. I can connect to both arm & leg devices (as BP5 device). Then when trying to get AbiControl it always returns null as well as calls to AbiControl.getAbiConnectedForArm(), AbiControl.getAbiConnected(). iOS app is notify about abi device and then it can retrieve AbiControl but no such thing happens in Android. 
Am I doing something wrong? What are the exact steps to retrieve AbiControl as it seems the CardioLab is not recognized as ABI device automatically.

**Comment by jzhw0130** [comment]
@padamuscinova 

Could you show me your work flow?

Step:
1. Discovery BP for arm and leg.
2. Connect them
3. 
//Get the mac address of arm blood pressure meter, if you only want to measure arm blood pressure.
        deviceMacForArm = AbiControl.getAbiConnectedForArm();
        //Get the mac address of leg blood pressure meter, if you  want to measure arm and len blood pressure at the same time (ABI).
        deviceMac = AbiControl.getAbiConnected();

4.  get abi control
     abiControl = iHealthDevicesManager.getInstance().getAbiControl(deviceMac);
5. Measure
     abiControl.startMeasure();

**Comment by padamuscinova** [comment]
Hello,

here is my workflow:

1. I don't use library discovery as my app is supporting multiple devices from other manufacturers too, so I use standard startDiscovery() method of BluetoothAdapter. Before making connection to the device I cancel the discovery (cancelDiscovery() method of BluetoothAdapter)
2. Connect to the the BP5s for arm and leg (one after another) using method of iHealthDeviceManager connectDevice(userName, macAddress, "BP5") - connection is successful for both devices DEVICE_STATE_CONNECTED
3. After both of them are connected successfully I tried calling:
a) AbiControl.getAbiConnectedForArm(); - returns null
b) AbiControl.getAbiConnected(); - returns null
c) iHealthDevicesManager.getInstance().getAbiControl(deviceMac); - returns null

I tried also Example app included in this repository - scan BP5 devices (iHealth scan), connected to both devices successfully, opening activity ABI.java by pressing "GOTOABI" button and again all calls mentioned in step 3 a) - c) return null.

**Comment by qqskim** [comment]
Hi


Could you call the api ( iHealthDevicesManager.getInstance().getDevicesIDPS(mac)  ) to get the information of connected devices?
Then send the son you got.

Moreover, 
public void onDeviceConnectionStateChange(String mac, String deviceType, int status, int errorID, Map manufactorData) {}
What’s the value of manufactorData for the connected devices?

Thanks


Jing

**Comment by padamuscinova** [comment]
Hello,

here are the results:

manufacturorData:
- same for leg & arm:
position -> unknown
subtype -> abi

IDPS:
- leg:
{"protocolstring":"com.jiuan.BPV21","accessoryname":"BPS5X","firmwareversion":"231","hardwareversion":"000","manufacture":"iHealth","serialnumber":"8CDE52425E40","modenumber":"BPS5X 11070"}
- arm:
{"protocolstring":"com.jiuan.BPV21","accessoryname":"BPS5X","firmwareversion":"230","hardwareversion":"000","manufacture":"iHealth","serialnumber":"8CDE5241FD37","modenumber":"BPS5X 11070"}

**Comment by qqskim** [comment]
OK

Get the problem.

@param manufactorData manufactorData Additional information for iHealth device   eg.  {subtype=abi, position=arm}.
*                       Attention: If (subtype=abi && position=unknown) , please charge the device fully， then tap the button for 10 seconds to reset the device.

**Comment by padamuscinova** [comment]
Hello, the resetting of the device helped, now everything works as expected. Thank you very much for your help. But I have still one question - why this happened?

**Comment by qqskim** [comment]
Sorry

It is a problem of device. If device is low battery, the problem will occur.
If you need more information, please contact our business manager:
Louie LYU <louie@ihealthlabs.com>  (Europe)
Yifan Liu <yifan.liu@ihealthlabs.com> (US)


Jing

**Comment by padamuscinova** [comment]
Ok, thank you for you help. The issue is resolved from my point of view.
