### ISSUE TITLE
Does the BP5 need firmware upgrade?

### ISSUE THREAD

**Issue by Frasprite** [iHealthDeviceLabs/iHealthDeviceLabs-Android#56]
Hello,

Francesco from **BEPATIENT DEV TEAM** here.

This is not an issue, but does the BP5 has a new firmware?
If yes, how we can do it with **iHealth SDK**?

Thank you in advance,
FB

**Comment by qqskim** [comment]
Hi

There is no new firmware for BP5.


Jing

**Comment by Frasprite** [comment]
Hi,

Great, thank you for your answer.

FB
