### ISSUE TITLE
iHealth geographic restrinctions

### ISSUE THREAD

**Issue by Frasprite** [iHealthDeviceLabs/iHealthDeviceLabs-Android#57]
Good morning,

Francesco from **BEPATIENT** DEV TEAM.
We have some client based in the USA, which are using our APP and iHealth devices (BP5).
They are not able to connect to device from there, but we are able with same device to use it here in France.
I was wondering: are there any problem / issue / restriction with geographic position of devices?

Thank you in advance,
FB

**Comment by qqskim** [comment]
Hi

What’s the version of SDK used?

Could you do a test with iHealth Demo on github?
Or update the latest version of SDK (V2.3.3)?  
Attention:  Update the libiHealth.so together with iHealthLibrary_2.3.3.jar.


Jing

**Comment by jzhw0130** [comment]
@Frasprite 

Any news?

**Comment by Frasprite** [comment]
Hi,

I have sent an APK to my coworker in the USA.

Thank you for your answer, I will give any feedback ASAP.

FB
