### ISSUE TITLE
Local Server SdkUserInAuthor Issue

### ISSUE THREAD

**Issue by SimonRsc** [iHealthDeviceLabs/iHealthDeviceLabs-Android#58]
Hi,

I'm working on an application which is connected to an local server wamp.
I've some problem with SdkUserInAuthor , i always get userstatus : 5
I use userName, userId and userSecret from a registered app.
Is it linked to the local server ?
How can i solve that problem ?

Thanks !

**Comment by qqskim** [comment]
Hi

sdkUserAuthor link to iHealth server.
Could you send your cientID and account(email)?

We will check your application permission.

Jing

**Comment by SimonRsc** [comment]
Hi,

this is my clientID : c351188ebca545d3a54041511b89844b
ans my account : simon.raschetti@orange.fr
