### ISSUE TITLE
Wrong date format received from AM3S device

### ISSUE THREAD

**Issue by ipodib** [iHealthDeviceLabs/iHealthDeviceLabs-Android#59]
One of our user have a strange issue. Activity tracker returned measurement with wrong date format: "2019-13-19 19:18:00".

As you can see this date from future and have 13 months. As a result we can't parse this date.
Any thoughts?

**User information:**
OS Version: 5.1.1
Model: LG Leon 4G LTE

Unfortunately we can't provide logs or any other information, since it happened on production app.

**Comment by zhaoyongguang** [comment]
Hi
I'm very sorry for the inconvenience.

What's the version of SDK used?
What's the FirmWare and HardWard of the Tracker?
Can you test you app with this SDK lib [iHealthLibrary_2.3.3_log.jar](https://github.com/iHealthDeviceLabs/iHealthDeviceLabs-Android/blob/master/lib/iHealthLibrary_2.3.3_log.jar) and then send me the log file?

**Comment by ipodib** [comment]
Unfortunately I wasn't able to reproduce this issue, but we have fact that user received this wrong date format. Also we don't know firmware and hardware versions. SDK Version 2.3.2 were used.

I'm just asking is there some cases when this issue can occur. Maybe we can find some root of cause.

Unfortunately, we have limited information about this issue.

**Comment by zhaoyongguang** [comment]
We know that, only one case, the use of the lunar calendar may cause this problem so far.

Is there any possible to get more info of the user such as user's timezone or location or calendar format?
If there is any progress, please let us know.

**Comment by ipodib** [comment]
All we know that the user's time zone is Eastern (ET). And actually Android does not allow a 13 month calendar in the system settings
