### ISSUE TITLE
Xamarin

### ISSUE THREAD

**Issue by gokulakshay** [iHealthDeviceLabs/iHealthDeviceLabs-Android#60]
Why dont you guys have separate sdks for Xamarin?

**Comment by zhaoyongguang** [comment]
@gokulakshay 
Thank you for your advice. We don't have the plan at the moment. But native and ReactNative SDKs for Android and iOS are now available.

**Comment by gokulakshay** [comment]
@zhaoyongguang Hey! Thanks for taking time to respond, I dint intend it to be a advice, It was just a question out of curiosity. With the increase in popularity of xamarin use, most people dont natively have libraries for Xamarin. Could you suggest me a quick workaround to use native android libs in a Xamarin project?

**Comment by zhaoyongguang** [comment]
@gokulakshay We plan to study Xamarin first and let you know when we make progress.

**Comment by gokulakshay** [comment]
Much appreciated ! Thanks
