### ISSUE TITLE
SDK not found

### ISSUE THREAD

**Issue by SadokLadhari** [iHealthDeviceLabs/iHealthDeviceLabs-Android#61]
Hi,

I can't find the iHealth SDK to test my android app.
I tried by email / developer site, but I didn't get back any response.

Please help me solving this issue.

**Comment by zhaoyongguang** [comment]
@SadokLadhari 

Please send me<sdk@ihealthlabs.com.cn> an e-mail with your personal email, and I will reply to you about what to do next.

**Comment by NarenLK** [comment]
Did you get the library?

**Comment by SadokLadhari** [comment]
@NarenLK I didn't get the library :(
