### ISSUE TITLE
Invalid Callback

### ISSUE THREAD

**Issue by D3laru3** [iHealthDeviceLabs/iHealthDeviceLabs-Android#62]
Hi, 
could you please add callback after this?
W/Runtime_iHealthDM: ConnectionThread -- Invalid callback
There is only warning log for that in iHealthDevicesManager$ConnectionThread and I don`t know how to react or notify user about it...

**Comment by D3laru3** [comment]
I realized that there is no way how to connect to device after Invalid callback message appears...I need to restart whole app...

**Comment by zhaoyongguang** [comment]
@D3laru3 
I'm sorry to inconvenience you. We  will update it soon.
By the way, which hardware device and the model of mobile phone do you use?
