### ISSUE TITLE
iHealthLibrary 2.3.4 ?

### ISSUE THREAD

**Issue by mfvn** [iHealthDeviceLabs/iHealthDeviceLabs-Android#63]
Hello, where can i download this library?
I already search but cannot find the jar file anywhere, only the 2.3.0.26
Thank you!

**Comment by NarenLK** [comment]
Did you get the Library ?

**Comment by mfvn** [comment]
@NarenLK No, I have sent an e-mail but there is no response yet

**Comment by NarenLK** [comment]
I guess they have taken down the SDK concept. They are bringing in "Layered app" concept

**Comment by mfvn** [comment]
@NarenLK Is there a guide on how to implement that ? thanks

**Comment by NarenLK** [comment]
@mfvn Not yet. Even i haven't got more detailed information on it.

**Comment by jialiabc** [comment]
@mfvn

Contact for more information:    
a. <yuchen.wang@ihealthlabs.com>(US)  
b. <noah@ihealthlabs.com>(Europe)  

Did you send an e-mail to correct person?

**Comment by mfvn** [comment]
@jialiabc yes, I am in europe so I contacted noah, I will try again

**Comment by jialiabc** [comment]
@mfvn 

Did you get the library now?

**Comment by mfvn** [comment]
Hello, yes but our app is still not approved so in a few days, after the trial time, we'll not be able to use it

**Comment by SadokLadhari** [comment]
@mfvn @jialiabc @NarenLK  I got this message from Noah : Unfortunately iHealth SDK is only for the B2B partners with an minimum commande 1000 products !!!
