### ISSUE TITLE
How to download SDK v2.3.5 ?

### ISSUE THREAD

**Issue by Frasprite** [iHealthDeviceLabs/iHealthDeviceLabs-Android#65]
Hi,

my name is Francesco Bevilacqua from **BEPATIENT** DEV Team.
I'm opening this issue because I didn't get any answer from given e-mail in the README file.

How can we download the latest version of your SDK ?

Regards,
FB

**Comment by jialiabc** [comment]
Hello Frasprite,

Did you ever get permission from iHealth team already?

If yes, please send me sdk@ihealthlabs.com.cn an e-mail with your personal email, your region, and I will reply to you about what to do next.

**Comment by Frasprite** [comment]
Hi @jialiabc ,

Thank you for your answer.
Yes, we have a permission from iHealth team (and also, we have an account on on iHealth developers site).
I will send you an email quickly.

Regards,
FB
