### ISSUE TITLE
iHealthDevicesCallback: RSSI is 0 on onScanDevice

### ISSUE THREAD

**Issue by Frasprite** [iHealthDeviceLabs/iHealthDeviceLabs-Android#67]
Hello,

Francesco Bevilacqua from **BEPATIENT** DEV Team.
In order to determine an approximate position of devices, we are thinking to use the RSSI signal on our code.
I use the callback method **onScanDevice()**, but I noticed that the _RSSI_ is always **0** when we search for BP5 and HS4S devices.
This is not the case for PO3.
Is there any options or another way to get the _RSSI_ from those devices ?

Thank you in advance,
FB

**Comment by jialiabc** [comment]
Hello
This case not work on BT devices, will always get 0. It is only work on BluetoothLe devices.

**Comment by Frasprite** [comment]
@jialiabc 
Hello, thank you for your answer.

Regards,
FB
