### ISSUE TITLE
Unknown user status

### ISSUE THREAD

**Issue by Frasprite** [iHealthDeviceLabs/iHealthDeviceLabs-Android#7]
Hi,

BePATIENT DEV team here.
We are current testing your v2.2.9 of your **Android SDK**.
As usual, before launching device discovering, we use following code in order to get _certification_:

    iHealthDevicesManager.getInstance().sdkUserInAuthor(MainActivity.this, userName, clientId, clientSecret, callbackId);

And we get a message indicating our status, but it is not really clear what is going on:

    06-21 11:34:12.543 19107-19730/com.example.devicelibtest I/System.out: 首次使用SDK,本地配置不存在!!!
    06-21 11:34:12.550 19107-19107/com.example.devicelibtest D/MainActivity: User status returned Bundle[{userstatus=8, username=name.secondname@bepatient.com}]

What does it mean?
Can you please help us with an explanation for the different 8 status?

Thank you in advance,
BePATIENT DEV Team

**Comment by manikavi** [comment]
**@Dev Team**,
  I'm also facing Same issue,Can You please help me to resolve this?

**Comment by jzhw0130** [comment]
@manikavi @Frasprite 

Could you supply your clientid client secret and username?
email: jingzhiwei@ihealthlabs.com.cn

**Comment by manikavi** [comment]
**@jzhw0130**,
             I have sent my credentials,Is this issue related to network ?

**Comment by jzhw0130** [comment]
@manikavi @Frasprite 

For the first time, sdk need to certificate your clientid clientsecret and username through our server.
So you need to have connect the internet for the first time.

For the next time,  internet will no need.

Status 8: means your internet is useless for the first certificate.

**Comment by jzhw0130** [comment]
@Frasprite @manikavi 
Your clientid clientsecret username is valid.

**Comment by Frasprite** [comment]
@jzhw0130 
Thank you for your answer.
What are the other 7 status?

**Comment by jzhw0130** [comment]
@Frasprite 

We will update the api document for user status.
User status: 
1.  New-user registration succeeded.
 2.  User login succeeded.
 3.  The user is iHealth user as well, measurement via SDK has been activated, and the data from the measurement belongs to the user. 
4. testing without Internet connection succeeded. 
5. Userid/clientID/clientSecret verification failed. 
6.  SDK has not been authorized. 
7. User has not been authorized. 
8.  Internet error, verification failed. 
–PS: The measurement via SDK will be operated in the case of 1-4, and will be terminated if any of 5-8 occurs. The interface needs to be re-called after analyzing the return parameters. @Notice By the first time of new user register via SDK, ‘iHealth disclaimer’ will pop up automatically, and require the user agrees to continue. SDK application requires Internet connection; there is 10-day tryout if SDK cannot connect Internet, SDK is fully functional during tryout period, but will be terminated without verification through Internet after 10 days.

**Comment by Frasprite** [comment]
Thank you so much, everything is clear now.
