### ISSUE TITLE
BP5 is stopped in middle of taking Measurement

### ISSUE THREAD

**Issue by manikavi** [iHealthDeviceLabs/iHealthDeviceLabs-Android#8]
Hi,
    
   BP5 device is stopped in middle of measurement,Please check the Log here

[06-22 09:11:19.038: **E/bt_btif_sock_rfcomm(1559): find_rfc_slot_by_id unable to find RFCOMM slot id: 15**
06-22 09:11:19.038: E/bt_rfcomm(1559): **p_data_co_callback DATA_CO_CALLBACK_TYPE_INCOMING_SIZE failed, available:0**
06-22 09:11:19.038: E/bt_btif_sock_rfcomm(1559): **find_rfc_slot_by_id unable to find RFCOMM slot id: 15**
06-22 09:11:19.063: W/System.err(19143): **java.io.IOException: bt socket closed, read return: -1**
06-22 09:11:19.063: W/System.err(19143): 	**at** **android.bluetooth.BluetoothSocket.read(BluetoothSocket.java:517)**
06-22 09:11:19.063: W/System.err(19143): 	**at android.bluetooth.BluetoothInputStream.read(BluetoothInputStream.java:96)**
06-22 09:11:19.063: W/System.err(19143): 	**at java.io.InputStream.read(InputStream.java:162)**
06-22 09:11:19.064: W/System.err(19143): at com.ihealth.communication.base.bt.BtCommThread.run(Unknown Source)](url)

*testing with Nexus 5,Andorid version is 6.0.1
*getting red Light(Abnormal Status) in ihealth BP5 device,

**Comment by jzhw0130** [comment]
@manikavi 
BP5 measure failed only on Nexus 5 with 6.0.1?  or failed with other Phone and other os version?
Thanks

**Comment by manikavi** [comment]
I was working in motorola with 5.1 version. Previously I tested only in that Phone.

**Comment by jzhw0130** [comment]
@manikavi 
One more question, with Nexus5 6.0.1, BP5 always measure failed, or sometimes?

**Comment by manikavi** [comment]
@jzhw0130  Only Once I got reading,after that it stopeed working

**Comment by jzhw0130** [comment]
Sorry , I cannot follow you.
Does BP5 stop work only once? or after the time, BP5 does not work again? 
Now,  BP5 works well  or not?

Red light on BP5 means BP5 cannot receive response from phone.
The log says: The communication socket closed . 
Did you try to reconnect BP5 again?

**Comment by manikavi** [comment]
@jzhw0130 ,
    Sorry for last response,I tried to reconnect also.taking measurement is stopped in middle,
How can i find out the reason for **"BT Socket Closed"**?

**Comment by manikavi** [comment]
@jzhw0130 
                     This Issue is resolved,I don't want my user to click twice for getting battery-level and taking measurement,So I placed getBattery(),startMeasure() methods inside same onclicklistener(see the code below).This is Causing an Issue,Is there any way to get both on same click?

	        case R.id.btn_startMeasurement:
			if(bp5Control != null){
				bp5Control.getBattery();
				bp5Control.startMeasure();
			}
			else{
				Toast.makeText(BP5.this, "bp5Control == null", Toast.LENGTH_LONG).show();
			}
			break;
](url)

**Comment by jzhw0130** [comment]
@manikavi 

Sorry for late reply.
You can do as follows:

case R.id.btn_startMeasurement:
        if(bp5Control != null){
            bp5Control.getBattery();
        }
        else{
            Toast.makeText(BP5.this, "bp5Control == null", Toast.LENGTH_LONG).show();
        }

@Override
        public void onDeviceNotify(String mac, String deviceType,
                                   String action, String message) {
            if(BpProfile.ACTION_BATTERY_BP.equals(action)){
                     if(bp5Control != null){
                          bp5Control.startMeasure();
                     }
                    else{
                           Toast.makeText(BP5.this, "bp5Control == null", Toast.LENGTH_LONG).show();
                     }
            }
